### ISSUE TITLE
[BUG] Fails to detect existing configuration and overwrites it with default template

### ISSUE THREAD

**Issue by redeven** [jammsen/docker-palworld-dedicated-server#10]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

Despite having existing config files mounted, it fails to detect them and overwrites them with the template, every single time.
This has started happening today (likely related to #5), after the docker image was updated.

### Desired behavior

Existing mounted config files should be respected.

### Links to screenshots

![image](https://github.com/jammsen/docker-palworld-dedicated-server/assets/18680184/723bd984-634f-4ed9-9371-e53d0e860a35)

### To Reproduce

1. Launch the docker container to generate config files, then shut it down
2. Change config files as needed
3. Launch the docker container again
4. Config is overwritten by template

### Software setup

- OS: Ubuntu 22.04.3 LTS
- Docker: Docker 24.0.5, Docker Compose 1.29.2

### Hardware setup

- CPU: Intel i7-10710U (6C/12T)
- RAM: 32gb
- Disk: 2 TB nvme

**Comment by jammsen** [comment]
The standard config is copied every start on purpose, so you get the latest config and not a "not working server".
The usual stuff can be setup in the Docker-Compose file.
And yes #5 was the merge to help establish this setup.

**Comment by redeven** [comment]
The problem is that none of the config will ever survive a container restart, which is bad for a dedicated server. You'd never be able to config difficulty, rates or other configs if they're being replaced every boot.

Also, an empty password (on purpose because you want an empty password) on the env vars results in the default template password, which again, means you currently can't even access the server because the game itself also has a bug with asking for passwords (and also, you should  be able to just not have a password at all).
![image](https://github.com/jammsen/docker-palworld-dedicated-server/assets/18680184/54dc1255-eb21-4e29-8d30-7ea2244eeb12)
![image](https://github.com/jammsen/docker-palworld-dedicated-server/assets/18680184/50a58fd8-33c1-4f1f-955d-7dbf0f56d1b0)

It's not gonna be good practice to overwrite everything with defaults every time. It should be up to the server software itself to generate missing files, add missing properties, and if the server wont launch due to old config, up to the user to remove old config files and regenerate them. If they exist they should be prioritized.

**Comment by Lakio21** [comment]
I have the same issue and even after updated my compose file, the configuration file has not been modified with the compose values. I overwrote my compose env variables with the one in the readme.
This is quite annoying because it reset the server password the default one and so making players unable to join the server ...

**Comment by pierre-nicoli** [comment]
The latest version of the container allows for setting the SERVER_PASSWORD envvar, which should then be copied to the conf file :)

**Comment by alekm** [comment]
> The latest version of the container allows for setting the SERVER_PASSWORD envvar, which should then be copied to the conf file :)

On systems like TrueNAS Scale, the environment variable can't be blank.  So how can we make it a public server without a password?

**Comment by alekm** [comment]
> > The latest version of the container allows for setting the SERVER_PASSWORD envvar, which should then be copied to the conf file :)
> 
> On systems like TrueNAS Scale, the environment variable can't be blank. So how can we make it a public server without a password?

Disregard. Double quotes works.

**Comment by jammsen** [comment]
> I have the same issue and even after updated my compose file, the configuration file has not been modified with the compose values. I overwrote my compose env variables with the one in the readme. This is quite annoying because it reset the server password the default one and so making players unable to join the server ...

Hey @Lakio21 
This should defently be possible, update your docker-image please and maybe try a fresh docker-compose file from the template. I have testet this now surely 50+ times. If you have still problems let me know that we will get down to this.

**Comment by jammsen** [comment]
@redeven if have fixed a lot of bugs, this should be better now i hope, please review and let me know.

Please go ahead and test things.
New Docker-Compose File is needed.
You can find now examples in the README.md.
The docker-compose.yml was removed because of dublicate code.

**Comment by Lakio21** [comment]
@jammsen Sorry for the late reponse. It was a little urgent so I end up forking your repo and revert to the previous state to make the server quickly up and running. I will give it ago later when I have more free time.

**Comment by jammsen** [comment]
If this issue is solved, please give me feedback on the patch and please consider giving me a Star here and on Docker-Hub.

**Comment by jammsen** [comment]
*Ping*

**Comment by gchai** [comment]
What would be the best way to update the server options that are not covered by the env vars in the game? For example `bEnableFriendlyFire` or `GuildPlayerMaximum`? Thanks!

**Comment by redeven** [comment]
While setting it through the env var (which requires doing `SERVER_PASSWORD=""` with quotes as an empty var will fail and get overwritten) works, it "expands" for lack of a better word, during the replacement in the settings file.
![image](https://github.com/jammsen/docker-palworld-dedicated-server/assets/18680184/2a461251-3c93-49a3-8b6b-e95b0c54797f)
As you can see, on every boot, it adds extra quotes. The game server still seems to parse it as empty which is fine but it's definitely not the intended value replacement.

**Comment by jammsen** [comment]
Please use  `SERVER_PASSWORD=` @redeven 



> What would be the best way to update the server options that are not covered by the env vars in the game? For example `bEnableFriendlyFire` or `GuildPlayerMaximum`? When I edit the values, they get overwritten on launch.

@gchai If you need other variables you are free to open an issue and i will look into that OR you join the issue #29 which "maybe wants" to have a "dumb" or "manual" mode to not use ENVs but only the config-file itself to be manually edited. Not sure what the requestor really wanted. But a manual/dum mode would be possible, while the ENVs way is considered Best-Practice in all of Docker and K8s / [Twelve-Factor-App](https://12factor.net/config)

**Comment by gchai** [comment]
I can add all the variables in as a Env Var and make a PR!

**Comment by gchai** [comment]
#40 submitted!

**Comment by jammsen** [comment]
Hey @gchai 
Thats some nice work, are you already on the readme for this too?

**Comment by jammsen** [comment]
This behavior should be solved with https://github.com/jammsen/docker-palworld-dedicated-server/commit/8546c890a518c99ab9be13b35a876c01ddaa7bde#diff-3b41cd2eeb76ac64c4b71b9cc6b253b358ab737f50d54e333b631ca27357e98e 

Feel free to reopen the issue if the problem persists.

If you like this project, please consider giving this repo and the docker-hub-repo a Star.
