### ISSUE TITLE
[Bug Report] bad crontab line

### ISSUE THREAD

**Issue by wsaddede** [jammsen/docker-palworld-dedicated-server#100]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

When I first edited 'BACKUP_CRON_EXPRESSION'， I set it to '5 0 0/6 * * ? ',  
at this time the system reported an error, I decided to modify it to '0 * * * * * ', 
but the modification didn't work, it always showed the first '5 0 0/6 * * ? ', 
I can't find its config file in the folder ， how can I change it?

[2024-01-28T04:30:02+08:00] read crontab: cronlist         
[2024-01-28T04:30:02+08:00] bad crontab line: '5 0 0/6 * * ? /backupmanager.sh' (use -debug for details) 

### Desired behavior

Change the description of BACKUP_CRON_EXPRESSION.

### Links to screenshots

[2024-01-28T04:30:02+08:00] read crontab: cronlist         
[2024-01-28T04:30:02+08:00] bad crontab line: '5 0 0/6 * * ? /backupmanager.sh' (use -debug for details) 

### Software setup

- OS:
- Docker:

### Hardware setup

- vCPU: 
- RAM: 
- Disk:

**Comment by wsaddede** [comment]
![20240128044615](https://github.com/jammsen/docker-palworld-dedicated-server/assets/31440671/f1c04d41-bc58-4c4d-a63a-592315d7813e)

**Comment by jammsen** [comment]
Hey @wsaddede the cronlist gets written every time on start of the container. You can see this here: https://github.com/jammsen/docker-palworld-dedicated-server/blob/master/servermanager.sh#L343 

All you need to do is to change either the Env for your Docker run command or your Docker-Compose ENV and run docker-compose down and then docker-compose up.

**Comment by wsaddede** [comment]
☆⌒(*＾-゜)v  THX!!

**Comment by jammsen** [comment]
Happy it helped!
