### ISSUE TITLE
[Bug Report] Synology NAS suffer from Permission Denied 

### ISSUE THREAD

**Issue by bravotok** [jammsen/docker-palworld-dedicated-server#101]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

Current behavior

When the script reaches the starting game server step it is unable to create a directory and other files

2024/01/28 05:19:14 | stderr | /servermanager.sh: line 327: ./PalServer.sh: No such file or directory
2024/01/28 05:19:14	stderr	/servermanager.sh: line 327: ./PalServer.sh: No such file or directory
2024/01/28 05:19:14	stdout	>>> Finished setting up PalWorldSettings.ini ...
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting BanListURL to https://api.palworldgame.com/api/banlist.txt
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting bUseAuth to true
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting Region to 
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting RCONPort to 25575
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting rcon-enabled to false
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting public ip to ***************
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting public port to 8211
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting server password to *************
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting server admin password to ********
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting server description to *******
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting server name to ***********
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting max-players to 16
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting CoopPlayerMaxNum to 8
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting bEnableDefenseOtherGuildPlayer to false
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting bExistPlayerAfterLogout to false
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting bIsStartLocationSelectByMap to true
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting bEnableFastTravel to true
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting bEnableNonLoginPenalty to true
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting bCanPickupOtherGuildDeathPenaltyDrop to false
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting bIsPvP to true
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting bIsMultiplay to false
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting WorkSpeedRate to 1.000000
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting PalEggDefaultHatchingTime to 0.000000
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting GuildPlayerMaxNum to 20
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting AutoResetGuildTimeNoOnlinePlayers to 72.000000
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting bAutoResetGuildNoOnlinePlayers to false
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting DropItemAliveMaxHours to 2.000000
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting BaseCampWorkerMaxNum to 30
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting BaseCampMaxNum to 1024
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting DropItemMaxNum_UNKO to 100
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting DropItemMaxNum to 3000
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting bEnableAimAssistKeyboard to false
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting bEnableAimAssistPad to true
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting bActiveUNKO to false
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting bEnableInvaderEnemy to true
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting bEnableFriendlyFire to false
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting bEnablePlayerToPlayerDamage to true
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting DeathPenalty to None
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting EnemyDropItemRate to 1.000000
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting CollectionObjectRespawnSpeedRate to 1.000000
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting CollectionObjectHpRate to 1.000000
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting CollectionDropRate to 1.000000
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting PalAutoHpRegeneRateInSleep to 1.000000
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting BuildObjectDeteriorationDamageRate to 1.000000
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting BuildObjectDamageRate to 1.000000
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting PalAutoHpRegeneRateInSleep to 1.000000
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting PalAutoHPRegeneRate to 1.000000
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting PalStaminaDecreaceRate to 
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting PalStomachDecreaceRate to 1.000000
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting PlayerAutoHpRegeneRateInSleep to 1.000000
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting PlayerAutoHPRegeneRate to 1.000000
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting PlayerStaminaDecreaceRate to 1.000000
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting PlayerStomachDecreaceRate to 1.000000
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting PlayerDamageRateDefense to 1.000000
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting PlayerDamageRateAttack to 1.000000
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting PalDamageRateDefense to 1.000000
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting PalDamageRateAttack to 1.000000
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting PalSpawnNumRate to 1.000000
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting PalCaptureRate to 2.000000
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting ExpRate to 1.000000
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting NightTimeSpeedRate to 1.000000
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting DayTimeSpeedRate to 1.000000
2024/01/28 05:19:14	stderr	sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: Permission denied
2024/01/28 05:19:14	stdout	Setting Difficulty to None
2024/01/28 05:19:14	stderr	cp: failed to access '/palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini': Permission denied
2024/01/28 05:19:14	stderr	mkdir: cannot create directory '/palworld': Permission denied

### Desired behavior

I'm trying to use Docker (renamed to Container Manager recently) on a Synology Nas to run this image, however I've been suffering from this error, yet I can use your image on a fresh linux...
I believe it is the privilege isolation from Synology that should be responsible for this...
I just want I to work, however, I'm out of skills...

### To Reproduce

1. Get a Synology DS1821+(or other X86 Model)
2. Update it to the latest DSM
3. Try to run this via container manager

### Software setup

- OS: DSM 7.2.1-69057 Update 3
- Docker: Container Manger 20.10.23-1437

### Hardware setup

- vCPU: AMD Ryzen V1500B
- RAM: 32G
- Disk: 84TB

### Additional context

Thanks for reading this, I'm counting on your help

**Comment by rebek254** [comment]
got the same problem but not on synology, just debian 11

**Comment by rebek254** [comment]
Found my error (I am using Portainer) --> docker-compose.yaml --> volumes --> just a path with permissions for the directory (like /etc/palworld)

**Comment by bravotok** [comment]
> Found my error (I am using Portainer) --> docker-compose.yaml --> volumes --> just a path with permissions for the directory (like /etc/palworld)

Not this one, i've done this

**Comment by bravotok** [comment]
Solved

For synology user:

Add a user in DSM GUI named steam, with password
Make the folder you want to name, remember the path to it, then upload the docker-compose.yml to the dictionary in DSM GUI
Turn on SSH
Connect SSH with admin account
Type sudo -i and press Enter, this will let you use root account
Use cd to get into the path you made 
Type docker-compose order on the guide book from readme
Your server should be started to build

**Comment by jammsen** [comment]
Awesome you solved it! Thanks for sharing the solution!

**Comment by Eforen** [comment]
I am having the same problem but on Kuberneties with NFS share vol via CSI

**Comment by bravotok** [comment]
> I am having the same problem but on Kuberneties with NFS share vol via CSI

You may try the terminal way, with root access.

**Comment by Eforen** [comment]
> > I am having the same problem but on Kuberneties with NFS share vol via CSI
> 
> @Eforen Please dont necro, you already posted in #117 and we working on it to help you to .... 🤷‍♂️

This one seemed much more relevant as its the exact same errors I am getting so seems to not be fixed.
