### ISSUE TITLE
[Bug Report] Can´t enter the server again

### ISSUE THREAD

**Issue by Graydens2510** [jammsen/docker-palworld-dedicated-server#102]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

Server was running today without any problem.

Now I get this Log.
Not able to enter the server again.....restart didn´t fix the problem.

2024/01/27 23:52:55 | stdout | [S_API FAIL] Tried to access Steam interface STEAMAPPS_INTERFACE_VERSION008 before SteamAPI_Init succeeded.
2024/01/27 23:52:54 | stdout | [S_API FAIL] Tried to access Steam interface SteamFriends017 before SteamAPI_Init succeeded.
2024/01/27 23:52:54 | stdout | [S_API FAIL] Tried to access Steam interface SteamUser021 before SteamAPI_Init succeeded.
2024/01/27 23:52:54 | stdout | Setting breakpad minidump AppID = 2394010
2024/01/27 23:52:54 | stdout | dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
2024/01/27 23:52:54 | stdout | CAppInfoCacheReadFromDiskThread took 16 milliseconds to initialize
2024/01/27 23:52:54 | stdout | [S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
2024/01/27 23:52:53 | stdout | - Existing per-process limit (soft=18446744073709551615, hard=18446744073709551615) is enough for us (need only 18446744073709551615)
2024/01/27 23:52:53 | stdout | Increasing per-process limit of core file size to infinity.
2024/01/27 23:52:53 | stdout | - Existing per-process limit (soft=1048576, hard=1048576) is enough for us (need only 1048576)
2024/01/27 23:52:53 | stdout | Shutdown handler: initalize.
2024/01/27 23:52:53 | stdout | >>> Finished setting up PalWorldSettings.ini ...
2024/01/27 23:52:53 | stdout | Setting rcon-enabled to true
2024/01/27 23:52:53 | stdout | Setting public ip to 91.114.86.58
2024/01/27 23:52:53 | stdout | Setting public port to 8211
2024/01/27 23:52:53 | stdout | Setting server password to Wzm123456789
2024/01/27 23:52:53 | stdout | Setting server admin password to Wzm1234567890
2024/01/27 23:52:53 | stdout | Setting server description to Palworld-Dedicated-Server running in Docker by jammsen
2024/01/27 23:52:53 | stdout | Setting server name to WzmServer
2024/01/27 23:52:53 | stdout | Setting max-players to 32
2024/01/27 23:52:53 | stdout | Checking if config exists
2024/01/27 23:52:53 | stdout | >>> Setting up PalWorldSettings.ini ...
2024/01/27 23:52:53 | stdout | >>> Finished setting up Engine.ini ...
2024/01/27 23:52:53 | stdout | Found NetServerMaxTickRate parameter, chaning it to 120
2024/01/27 23:52:53 | stdout | Found [/Script/OnlineSubsystemUtils.IpNetDriver] section
2024/01/27 23:52:53 | stdout | >>> Setting up Engine.ini ...
2024/01/27 23:52:53 | stdout | >>> Starting the gameserver
2024/01/27 23:52:53 | stdout | Success! App '2394010' fully installed.
2024/01/27 23:52:52 | stdout | Update state (0x5) verifying install, progress: 88.72 (1994567924 / 2248045559)
2024/01/27 23:52:50 | stdout | Update state (0x5) verifying install, progress: 69.67 (1566228774 / 2248045559)
2024/01/27 23:52:48 | stdout | Update state (0x5) verifying install, progress: 49.82 (1120018453 / 2248045559)
2024/01/27 23:52:46 | stdout | Update state (0x5) verifying install, progress: 30.10 (676575843 / 2248045559)
2024/01/27 23:52:44 | stdout | Update state (0x5) verifying install, progress: 10.02 (225306005 / 2248045559)
2024/01/27 23:52:42 | stdout | Update state (0x5) verifying install, progress: 0.19 (4194304 / 2248045559)
2024/01/27 23:52:42 | stdout | Waiting for user info...OK
2024/01/27 23:52:42 | stdout | Waiting for client config...OK
2024/01/27 23:52:41 | stdout | Connecting anonymously to Steam Public...OK
2024/01/27 23:52:40 | stdout |  
2024/01/27 23:52:40 | stdout | Loading Steam API...OK
2024/01/27 23:52:40 | stdout | -- type 'quit' to exit --
2024/01/27 23:52:40 | stdout | Steam Console Client (c) Valve Corporation - version 1705108307
2024/01/27 23:52:40 | stdout | [----] Verifying installation...
2024/01/27 23:52:39 | stdout | [  0%] Checking for available updates...
2024/01/27 23:52:39 | stdout | Logging directory: '/home/steam/Steam/logs'
2024/01/27 23:52:39 | stdout | Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
2024/01/27 23:52:39 | stdout | tid(19) burning pthread_key_t == 0 so we never use it
2024/01/27 23:52:39 | stdout | [36mINFO[0m[2024-01-27T23:52:39+01:00] read crontab: cronlist
2024/01/27 23:52:39 | stdout | >>> Doing an update of the gameserver
2024/01/27 23:52:39 | stdout | >>> Checking for existence of default credentials
2024/01/27 23:52:32 | stdout | Shutdown handler: cleanup.
2024/01/27 23:52:32 | stdout |  
2024/01/27 23:52:29 | stdout |  
2024/01/27 23:52:29 | stdout | FUnixPlatformMisc::RequestExitWithStatus
2024/01/27 23:49:13 | stdout | [S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.
2024/01/27 23:49:13 | stdout | [S_API FAIL] Tried to access Steam interface STEAMAPPS_INTERFACE_VERSION008 before SteamAPI_Init succeeded.
2024/01/27 23:49:12 | stdout | [S_API FAIL] Tried to access Steam interface SteamFriends017 before SteamAPI_Init succeeded.
2024/01/27 23:49:12 | stdout | [S_API FAIL] Tried to access Steam interface SteamUser021 before SteamAPI_Init succeeded.

</body>
</html>

### Desired behavior

c

### Software setup

- OS:
- Docker:

### Hardware setup

- vCPU: 
- RAM: 
- Disk:

**Comment by jammsen** [comment]
Hey @Graydens2510 can you please provide more information? No HW, no SW, no Screenshot or Error. How should i be able to help you?

**Comment by jammsen** [comment]
Please create a new issue with information that enable me to help you.
