### ISSUE TITLE
[S_API FAIL] Tried to access Steam interface SteamUser021 before SteamAPI_Init succeeded.

### ISSUE THREAD

**Issue by pllydong** [jammsen/docker-palworld-dedicated-server#11]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

This problem occurs when I enter the game, and it prompts "no password has been entered." I deleted the password options directly in the docker-compose file, deleted the game folder, and reinitialized it. However, when entering the game, it still prompts "no password has been entered." How can I solve this issue?

### Desired behavior

What should I do?

### Links to screenshots

![Snipaste_2024-01-21_11-05-22](https://github.com/jammsen/docker-palworld-dedicated-server/assets/140327258/83b456ed-471f-45bf-89bf-a66242565f71)

### Software setup

- OS: debian
- Docker:  Docker version 20.10.24+dfsg1, build 297e128

### Hardware setup

- vCPU: 5800H
- RAM: 32G
- Disk:2T

**Comment by Yzzzed** [comment]
same problem

**Comment by pierre-nicoli** [comment]
This is a know issue from the Client: when you type in a server address yourself and it has a password set, you are not prompted for the server password.
By default, there is a password on the config file.

**If you absolutely need a password:**
- enable community listing of your dedicated server
- search for your server (and there is a known bug that makes it hard since it only searches on the current "page", so you have to paginate, then search, then paginate, then search...)
- connect with your password from there
- alternatively, wait for a client fix

**If you don't need a server passsword, either:**
- reset your config and use the brand new SERVER_PASSWORD env option to set it to ""
- or go to your `Pal/Saved/Config/LinuxServer/PalWorldSettings.ini` file and change the ServerPassword to ""

**Comment by pllydong** [comment]
> This is a know issue from the Client: when you type in a server address yourself and it has a password set, you are not prompted for the server password. => see https://primagames.com/tips/how-to-fix-palworld-no-password-has-been-entered-error By default, there is a password on the config file.
> 
> **If you absolutely need a password:**
> 
> * enable community listing of your dedicated server
> * search for your server (and there is a known bug that makes it hard since it only searches on the current "page", so you have to paginate, then search, then paginate, then search...)
> * connect with your password from there
> * alternatively, wait for a client fix
> 
> **If you don't need a server passsword, either:**
> 
> * reset your config and use the brand new SERVER_PASSWORD env option to set it to ""
> * or go to your `Pal/Saved/Config/LinuxServer/PalWorldSettings.ini` file and change the ServerPassword to ""

The mentioned "fail" messages do not affect the final entry into the game. The initial issue of not being able to enter the game was due to a password problem.

**Comment by jammsen** [comment]
Thanks for the help @pierre-nicoli

**Comment by GaretGaret** [comment]
Also having this problem! While I hope to be able to have a password in future, I wanted to test the server running and so tried to set up without one. I have edited the config file SERVER_PASSWORD line to be both completely blank after the equal sign, and also with a double quote ("") - even though I assume the latter is really equal to having nothing. Log continues to throw the same error messages:

palworld-dedicated-server  | [S_API FAIL] Tried to access Steam interface SteamUser021 before SteamAPI_Init succeeded.
palworld-dedicated-server  | [S_API FAIL] Tried to access Steam interface SteamFriends017 before SteamAPI_Init succeeded.
palworld-dedicated-server  | [S_API FAIL] Tried to access Steam interface STEAMAPPS_INTERFACE_VERSION008 before SteamAPI_Init succeeded.
palworld-dedicated-server  | [S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.

Appreciate any suggestions!

**Comment by pierre-nicoli** [comment]
@GaretGaret, as mentioned in the README.md, this message is of absolutely not importance (it is linked to the SteamCMD steam headless client, and the the server app itself). The config file, do you mean the one that is recreated each time you restart the docker container ?
You need to either change it in the proposed docker-compose.yml file in the repo OR explicitely set the envvar on your docker run command.
