### ISSUE TITLE
[Feature Request] Add minimum and recommended specs for the Palworld dedicated server in your readme

### ISSUE THREAD

**Issue by dantheman213** [jammsen/docker-palworld-dedicated-server#115]
### Have you read the Important information text above

- [X] Yes i did

### Describe the feature

Add minimum and recommended specs for the Palworld dedicated server in your readme. This will help new people coming into the game to know what kind of hardware they need to provision or setup to run the community server. Perhaps have it with a table showing minimum/recommended by player count or some other metric that affects performance.

### Additional information

- [ ] Would you be willing to help implement this feature?

### Final checks

- [X] I understand that this is a feature request function. I also unterstand that if i use this to report a bug report, that my issue might be un-answered closed.

**Comment by jammsen** [comment]
Hey @dantheman213 that would be no problem at all and i would really want this.

But i dont have anything official as a source what theese specs are, do you know any sources for this?
I dont want to spread miss-information from my testing that works for me and my CPU/RAM/SSDs.

**Comment by miaulightouch** [comment]
read this gist from community:

- https://gist.github.com/Toakan/3c78a577c21a21fcc5fa917f3021d70e

**Comment by jammsen** [comment]
Added in #115

**Comment by dantheman213** [comment]
Here are the requirements listed in their [official documentation](https://tech.palworldgame.com/dedicated-server-guide#requirement)

>Requirements
> 
> CPU	4Cores (recommend)
> 
> RAM	16GB
> Recommend over 32GB for stable operation.
> It is possible to start the server with 8 GB, but the further you play, the server will crash due to out of memory.
> 
> Network	UDP Port 8211 (Default) Port forwarding required.

**Comment by jammsen** [comment]
@dantheman213 yes thanks i did see that, but wanted to create a like scaling for hardware to players on the server and the config  and that only source is very static 👍
