### ISSUE TITLE
[Bug Report] PAL_AUTO_HP_REGENE_RATE_IN_SLEEP replaced by other var

### ISSUE THREAD

**Issue by TsunaLamperouge** [jammsen/docker-palworld-dedicated-server#116]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

In the script theres an extra SED command to replace PAL_AUTO_HP_REGENE_RATE_IN_SLEEP with the BUILD_OBJECT_DETERIORATION_DAMAGE_RATE value.

### Desired behavior

PAL_AUTO_HP_REGENE_RATE_IN_SLEEP only being replaced by its own environment var.

### To Reproduce

Line 152 of servermanager.sh

`        if [[ ! -z ${BUILD_OBJECT_DETERIORATION_DAMAGE_RATE+x} ]]; then
            echo "> Setting PalAutoHpRegeneRateInSleep to $BUILD_OBJECT_DETERIORATION_DAMAGE_RATE"
            sed -E -i "s/PalAutoHpRegeneRateInSleep=[+-]?([0-9]*[.])?[0-9]+/PalAutoHpRegeneRateInSleep=$BUILD_OBJECT_DETERIORATION_DAMAGE_RATE/" ${GAME_PATH}/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini
        fi
`

### Software setup

- OS: Linux
- Docker: 

### Hardware setup

- vCPU: 4
- RAM: 16Gb
- Disk:400gb

**Comment by tipanic** [comment]
Thank your for pointing this out, thought something was off but couldn't figure it out. 
I just checked my PalWorldSettings.ini
BUILD_OBJECT_DETERIORATION_DAMAGE_RATE is set "0" but PAL_AUTO_HP_REGENE_RATE_IN_SLEEP also.

**Comment by tipanic** [comment]
I changed the values to the following in the servermanager.sh on my environment, started the container, and its now working as it should.

    if [[ ! -z ${PAL_AUTO_HP_REGENE_RATE_IN_SLEEP+x} ]]; then
        echo "Setting PalAutoHpRegeneRateInSleep to $PAL_AUTO_HP_REGENE_RATE_IN_SLEEP"
        sed -E -i "s/PalAutoHpRegeneRateInSleep=[+-]?([0-9]*[.])?[0-9]+/PalAutoHpRegeneRateInSleep=$PAL_AUTO_HP_REGENE_RATE_IN_SLEEP/" ${GAME_PATH}/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini fi
