### ISSUE TITLE
`/home/steam/steamcmd/steamcmd.sh: line 39:    11 Segmentation fault      $DEBUGGER "$STEAMEXE" "$@"`

### ISSUE THREAD

**Issue by devioa** [jammsen/docker-palworld-dedicated-server#12]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

start failed: `/home/steam/steamcmd/steamcmd.sh: line 39:    11 Segmentation fault      $DEBUGGER "$STEAMEXE" "$@"`

### Desired behavior

successfully started server

### Links to screenshots

![image](https://github.com/jammsen/docker-palworld-dedicated-server/assets/38558065/d828c087-8307-48cb-af2a-4ddc2ce5d4a8)

### To Reproduce

docker run

### Software setup

- OS: `Linux OpenWrt 6.1.73 #0 SMP PREEMPT_DYNAMIC Thu Jan 18 09:40:58 2024 x86_64 GNU/Linux`
- Docker: 
```
# docker version
Client:
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.21.5
 Git commit:        afdd53b
 Built:             Thu Jan 18 09:40:58 2024
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.21.5
  Git commit:       311b9ff
  Built:            Thu Jan 18 09:40:58 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.6
  GitCommit:
 runc:
  Version:          1.1.9
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Hardware setup

- vCPU: Intel(R) Celeron(R) N5105 @ 2.00GHz : 4C4T
- RAM: 4GB
- Disk: SSD

**Comment by jammsen** [comment]
Could you do please a fresh docker-image, compose file and install and check if your storage has at least 10GB free?

**Comment by devioa** [comment]
I now know the reason. Steam cmd only has 32-bit executable binary files, while OpenWrt only supports 64 bit programs, so it cannot run.

**Comment by jammsen** [comment]
Thanks for sharing the answer!

**Comment by MathysLioson** [comment]
> I now know the reason. `steamcmd` only has 32-bit executable binary files, while OpenWrt only supports 64 bit programs, so it cannot run.

Is there a way to run 64-bit excutable binary files for steamcmd ? Or did you find a solution for make the things work ?

**Comment by devioa** [comment]
> > I now know the reason. `steamcmd` only has 32-bit executable binary files, while OpenWrt only supports 64 bit programs, so it cannot run.
> 
> Is there a way to run 64-bit excutable binary files for steamcmd ? Or did you find a solution for make the things work ?

no, but I created an Ubuntu virtual machine using VMware ESXi and ran it
