### ISSUE TITLE
[Bug Report] Your descriptivMy server is not listed on the community server liste title here!

### ISSUE THREAD

**Issue by dakezuo** [jammsen/docker-palworld-dedicated-server#121]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

COMMUNITY_SERVER has been set to true, but the list of community servers can not be searched, the server can enter the play normally, does this need to change any Settings? Or is there a port that needs to be cleared?

### Desired behavior

My server appears in the community list

### To Reproduce

readme setup

### Software setup

- OS:ubuntu22.04
- Docker:

### Hardware setup

- vCPU: 1700x
- RAM: 32G
- Disk:250G

**Comment by Compupaq** [comment]
It's an issue with Palworld itself.  The game only loads a list of 200 community servers and only searches among that list of 200.  You can try refreshing the list to pull in different servers, but chances are low that you'll see yours.

**Comment by dakezuo** [comment]
@Compupaq  
I can't search it on https://www.battlemetrics.com/servers/palworld, this article also can search 200 number?

**Comment by jammsen** [comment]
Hey @dakezuo if you can enter from an external open ip and play, then your server should be listed in EOS when you enabled Community-Mode. What @Compupaq writes is true, Palworld has a really weird server-browser that needs some work. Also sometimes the EOS servers a quite stressed and you could try to search for your server on https://www.battlemetrics.com/servers/palworld - yes thats true, but give i like 30-60m.

Aside from that there isnt, anything i can do, aside from explaining it to you 😢

**Comment by jammsen** [comment]
Nice! Happy gaming! 😎
