### ISSUE TITLE
Documentation: Docker Compose Example with Portainer is listed twice

### ISSUE THREAD

**Issue by Compupaq** [jammsen/docker-palworld-dedicated-server#123]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

In the readme under Docker Compose examples, there's two sections for Nameserver with Portainer.  The first one listed appears to be a copy of the Gameserver with RCON example.

### Desired behavior

Only have one example for Portainer

### To Reproduce

Go here:
https://github.com/jammsen/docker-palworld-dedicated-server#gameserver-with-portainer
Then scroll down to find the second one.

### Software setup

N/A

### Hardware setup

N/A

**Comment by jammsen** [comment]
Hey @Compupaq 
yeah i noticed that yesterday while working on it with other contributors. 
Thanks for reporting it ❤️ .
Its fixed!

If you like this project, please consider giving this repo and the docker-hub-repo a Star.
