### ISSUE TITLE
[Bug Report] Cant fix small Bug in README.md !?

### ISSUE THREAD

**Issue by LuthorDevelopment** [jammsen/docker-palworld-dedicated-server#124]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

Hello,
I would have liked to fix a small link error in the README.md but can neither push a new branch nor a fix for the Develop-Branch....

### Desired behavior

Is it because of the permissions, or did I just try to push it wrong? Both would be possible :-) 

### To Reproduce

The Hyperlink in the Tutorial-Section linkes to #examples but the link-target has been renamed to #docker-compose-examples

### Software setup

Github :-) 

### Hardware setup

Github :-)

**Comment by thejcpalma** [comment]
Just have to wait for the PR to be approved m8 😅
Jamsmsen is on sabatical to resto so if you need to do changes just do a PR and He'll check when he's available

**Comment by LuthorDevelopment** [comment]
> Just have to wait for the PR to be approved m8 😅 Jamsmsen is on sabatical to resto so if you need to do changes just do a PR and He'll check when he's available

I'm just not sure whether something else is causing it to fail. Normally I create a branch, push it into the repo and create a merge-request. I have never needed a pull request so far :D 

git push
ERROR: Permission to jammsen/docker-palworld-dedicated-server.git denied to LuthorDevelopment.
fatal: Could not read from remote repository.

Please make sure that you have the correct access permissions
and the repository exists.
To me this looks like a different problem :D Or I'm doing something fundamentally wrong :D

**Comment by jammsen** [comment]
Hey @LuthorDevelopment normally you just fork my repo, change it on your master or develop and create a PR against my master or develop. But im also not a Github Pro sorry 🤣 

Do you want to give me the line you having an issue with so i can fix it?

**Comment by jammsen** [comment]
> Just have to wait for the PR to be approved m8 😅
> Jamsmsen is on sabatical to resto so if you need to do changes just do a PR and He'll check when he's available

Thanks 😄 also "jammsen" is my prefered way, the "Jammsen" feels just off to me 🤣
