### ISSUE TITLE
[Bug Report] DEATH_PENALTY config bug

### ISSUE THREAD

**Issue by Seimann** [jammsen/docker-palworld-dedicated-server#125]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

I want to set "DEATH_PENALTY" to 1 (drop only items). A 1 is added every time you restart.
In the config: **DEATH_PENALTY=1**
In PalWorldSettings.ini: **DeathPenalty=111**
next restart=1111

"DEATH_PENALTY=Items" no longer works, this is "1"
Now i set SERVER_SETTINGS_MODE to "manual"

### Desired behavior

DeathPenalty=1

### Software setup

- OS: Ubuntu Server 22.04
- Docker: 25.0.1

### Hardware setup

- vCPU: 8
- RAM: 32
- Disk: 500GB

**Comment by CleryMenuel** [comment]
"None : No lost
Item : Lost item without equipment
ItemAndEquipment : Lost item and equipment
All: Lost All item, equipment, pal(in inventory)"

If you want to lose that the Items (without equipment) you can write: 
DEATH_PENALTY=Item

**Comment by jammsen** [comment]
Hey @Seimann 
As @CleryMenuel already wrote, "DeathPenalty" is an Enum, it only can hold and use specific values and act on that. You need to enter the correct text-value for it.

Also you should stop the server, edit config and start it again. Not sure how you added a lot of "1" to your config 🤣 

I just tested both, it works in manual or auto mode.

Im closing this issue as resolved, feel free to reach out again if you need help.

If you like this project, please consider giving this repo and the docker-hub-repo a Star.
