### ISSUE TITLE
steamcmd: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by zhao-wuyan** [jammsen/docker-palworld-dedicated-server#13]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

Steamcmd: cannot execute binary file: Exec format error and then No such file or directory
UGREEN NAS is used

### Desired behavior

normal operation 

### Links to screenshots

![Clip_2024-01-21_17-49-27](https://github.com/jammsen/docker-palworld-dedicated-server/assets/59789646/1b3cb9fb-d3ce-44dd-8479-00720c3dc325)

### To Reproduce

Directly run 100% reproduction 

### Software setup

- OS: Linux UGREEN-E563 5.10.120 #0 SMP Fri Dec 29 03:07:23 2023 x86_64 GNU/Linux
- Docker: Docker version 20.10.16, build aa7e414

### Hardware setup

- vCPU: Intel(R) Pentium(R) Silver N6005 @ 2.00GHz
- RAM: 8+16
- Disk:
> /dev/dm-0               465.5G      4.9G    460.7G   1% /mnt/dm-0
> /dev/dm-1                12.7T      3.4T      9.4T  27% /mnt/dm-1
> /dev/dm-2               931.1G     80.3G    850.7G   9% /mnt/dm-2
> /dev/dm-3               931.1G    429.1G    501.9G  46% /mnt/dm-3
> /dev/dm-4                 7.3T      3.8T      3.4T  53% /mnt/dm-4

### Additional context

[
    {
        "Id": "624dcc0310290cdb6adbd5b5f76ad84ca24388ba1f0339b9aca6b6537ddc5355",
        "Created": "2024-01-21T09:39:02.179784799Z",
        "Path": "/servermanager.sh",
        "Args": [],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 127,
            "Error": "",
            "StartedAt": "2024-01-21T09:39:03.646234758Z",
            "FinishedAt": "2024-01-21T09:39:03.65898544Z"
        },
        "Image": "sha256:eeec45f90325dd9fba8b142f5340e4582186b885e2617399bd2569a7fed517ee",
        "ResolvConfPath": "/mnt/dm-2/.ugreen_nas/6/containers/624dcc0310290cdb6adbd5b5f76ad84ca24388ba1f0339b9aca6b6537ddc5355/resolv.conf",
        "HostnamePath": "/mnt/dm-2/.ugreen_nas/6/containers/624dcc0310290cdb6adbd5b5f76ad84ca24388ba1f0339b9aca6b6537ddc5355/hostname",
        "HostsPath": "/mnt/dm-2/.ugreen_nas/6/containers/624dcc0310290cdb6adbd5b5f76ad84ca24388ba1f0339b9aca6b6537ddc5355/hosts",
        "LogPath": "/mnt/dm-2/.ugreen_nas/6/containers/624dcc0310290cdb6adbd5b5f76ad84ca24388ba1f0339b9aca6b6537ddc5355/624dcc0310290cdb6adbd5b5f76ad84ca24388ba1f0339b9aca6b6537ddc5355-json.log",
        "Name": "/palworld-dedicated-server",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "8211/udp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8211"
                    },
                    {
                        "HostIp": "::",
                        "HostPort": "8211"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": [
                "AUDIT_WRITE",
                "CHOWN",
                "DAC_OVERRIDE",
                "FOWNER",
                "FSETID",
                "KILL",
                "MKNOD",
                "NET_BIND_SERVICE",
                "NET_RAW",
                "SETUID",
                "SETGID"
            ],
            "CapDrop": [],
            "CgroupnsMode": "private",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "Mounts": [
                {
                    "Type": "bind",
                    "Source": "/mnt/media_rw/19f2a024-6119-438d-ba72-5975dbdd3a1a/.ugreen_nas/248447/Docker/GAME-SEVER/palworld-server/game",
                    "Target": "/palworld",
                    "Consistency": "default"
                }
            ],
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/mnt/dm-2/.ugreen_nas/6/overlay2/914cb8284fa0100e188c30cb45123891e88179e119b0029482a90c608f433ad9-init/diff:/mnt/dm-2/.ugreen_nas/6/overlay2/663ee0298cc8b6179c0cf9c4e01eb68c8b12fdccac561e1d6c5dc799566559ab/diff:/mnt/dm-2/.ugreen_nas/6/overlay2/b7bd5fb6e1082f0b43199a86bfc13cd3d81f88351c9c70b9a7aee68917f69684/diff:/mnt/dm-2/.ugreen_nas/6/overlay2/b89d2a2ee56e04305b71f8162171f5cbf1f9bad656548e318e0ec031172b0312/diff:/mnt/dm-2/.ugreen_nas/6/overlay2/bfd9c68024d53ef754ebd477d8a0f47dc9a285531f6355503943c0b2315cdeaa/diff",
                "MergedDir": "/mnt/dm-2/.ugreen_nas/6/overlay2/914cb8284fa0100e188c30cb45123891e88179e119b0029482a90c608f433ad9/merged",
                "UpperDir": "/mnt/dm-2/.ugreen_nas/6/overlay2/914cb8284fa0100e188c30cb45123891e88179e119b0029482a90c608f433ad9/diff",
                "WorkDir": "/mnt/dm-2/.ugreen_nas/6/overlay2/914cb8284fa0100e188c30cb45123891e88179e119b0029482a90c608f433ad9/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/mnt/media_rw/19f2a024-6119-438d-ba72-5975dbdd3a1a/.ugreen_nas/248447/Docker/GAME-SEVER/palworld-server/game",
                "Destination": "/palworld",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "61c48d8ffd0b",
            "Domainname": "",
            "User": "steam",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8211/udp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "USER=steam",
                "HOMEDIR=/home/steam",
                "STEAMCMDDIR=/home/steam/steamcmd",
                "TIMEZONE=Europe/Berlin",
                "DEBIAN_FRONTEND=noninteractive",
                "PUID=1000",
                "PGID=1000",
                "ALWAYS_UPDATE_ON_START=false",
                "MAX_PLAYERS=32",
                "MULTITHREAD_ENABLED=true",
                "COMMUNITY_SERVER=false",
                "PUBLIC_IP=0.0.0.0",
                "PUBLIC_PORT=8211",
                "SERVER_NAME=jammsen-docker-generated-###RANDOM###",
                "SERVER_DESCRIPTION=Palworld-Dedicated-Server running in Docker by jammsen",
                "SERVER_PASSWORD=serverPasswordHere",
                "ADMIN_PASSWORD=adminPasswordHere"
            ],
            "Cmd": [
                "/servermanager.sh"
            ],
            "Healthcheck": {},
            "Image": "jammsen/palworld-dedicated-server:latest",
            "Volumes": {
                "/palworld": {}
            },
            "WorkingDir": "/home/steam/steamcmd",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "maintainer": "walentinlamonos@gmail.com",
                "org.opencontainers.image.authors": "Sebastian Schmidt",
                "org.opencontainers.image.source": "https://github.com/jammsen/docker-palworld-dedicated-server"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "2b81136387e8229356c4ab0efd7719b1eda59e02260f80826da703ba5ab6b96a",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/2b81136387e8",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "5304ff48af8f0348b7e736c5195e9fda4a7743e6b7014ea3c65b83c4bedb147c",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by pierre-nicoli** [comment]
Seems you're missing attaching a local directory to the /palworld container volume.

**Comment by jammsen** [comment]
Hey @pierre-nicoli - No i think it is mounted 

> "Mounts": [
{
"Type": "bind",
"Source": "/mnt/media_rw/19f2a024-6119-438d-ba72-5975dbdd3a1a/.ugreen_nas/248447/Docker/GAME-SEVER/palworld-server/game",
"Target": "/palworld",
"Consistency": "default"
}
],

Hey @zhao-wuyan - Try to give the `game` permission via CHOWN or CHMOD like the readme explains.

**Comment by jammsen** [comment]
Sounds very exotic, not sure how to help with that. Sorry.

**Comment by Koolercat** [comment]
需要注意的是，SteamCMD 仅提供 32 位二进制文件。如果您的系统仅能运行 64 位进程（例如 OpenWRT 系统），将不能正常使用。
[https://blog.towind.fun/posts/run-dont-starve-server/](https://github.com/kairlec/dst-admin-go-docker/issues/url)

我看你的系统是绿联，可能是同样的问题。
