### ISSUE TITLE
[Feature Request] Backup retention time

### ISSUE THREAD

**Issue by OliveiraNt** [jammsen/docker-palworld-dedicated-server#138]
### Have you read the Important information text above

- [X] Yes i did

### Describe the feature

I think it would be a useful to put an option to remove old backups to avoid disk space waste.

I currently use something like this on my server:

`0 0 * * * find ${BACKUP_DIR} -type f -mtime +${DAYS_TO_RETAIN} -exec rm {} \;`

It could other cron or be added to `backupmanager.sh` to run after.

Something like:

```
#!/bin/bash

DATE=$(date +%Y%m%d_%H%M%S)
TIME=$(date +%H-%M-%S)

echo ">>> Creating backup"
echo "> Sending message to gameserver"
cd ~/steamcmd/
rconcli "broadcast $TIME-Backup_in_progress"
sleep 1
rconcli 'broadcast Saving...'
rconcli 'save'
rconcli 'broadcast Done...'
sleep 15
# Create backup dir and change into it
mkdir -p /palworld/backups && cd /palworld/Pal
tar cfz /palworld/backups/saved-$DATE.tar.gz Saved/
echo ">>> Done"
if [[ -n $DAYS_TO_RETAIN ]] && [[ ! $DAYS_TO_RETAIN -eq 0 ]]; then #Avoid removing all files if defined as 0
    echo ">>> Removing old backups"
    find  /palworld/backups -type f -mtime +${DAYS_TO_RETAIN} -exec rm {} \;
    echo ">>> Done"
fi

```

### Additional information

- [ ] Would you be willing to help implement this feature?

### Final checks

- [X] I understand that this is a feature request function. I also unterstand that if i use this to report a bug report, that my issue might be un-answered closed.

**Comment by jammsen** [comment]
Hey @OliveiraNt 
Im working on this right now but dont want to use date for this. More like combination of sorts.

The solution will be like "keep the last X backups" sort of way.

**Comment by jammsen** [comment]
See also here https://github.com/jammsen/docker-palworld-dedicated-server/issues/27#issuecomment-1910988596

**Comment by jammsen** [comment]
This was just fixed - See https://github.com/jammsen/docker-palworld-dedicated-server/issues/27#issuecomment-1916979966

Im closing this issue as resolved, feel free to try it out and reopen again if needed.

If you like this project, please consider giving this repo and the docker-hub-repo a Star.
