### ISSUE TITLE
Docker shutdown signal not passed on

### ISSUE THREAD

**Issue by uncaught** [jammsen/docker-palworld-dedicated-server#14]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

When stopping the container, it seems to get killed after the `stop_grace_period` (default 10s).

### Desired behavior

The stop signal should be passed onto the underlying service so that it shuts down cleanly within the grace period.

If the clean shutdown takes longer than 10 seconds, the image should set a higher grace period.

### To Reproduce

1. Stop the container
4. See it always stops after 10 seconds

### Software setup

- OS: Ubuntu 22.04
- Docker: 24.0.4
- Docker compose: 2.19.1

### Hardware setup

- vCPU: 6
- RAM: 16G
- Disk: 280G SSD

**Comment by 0Downtime** [comment]
This would be helpful since the server needs rebooted every 2 hours due to memory leak.

**Comment by jammsen** [comment]
Hey @uncaught 
Looks to me like this is the problem? https://docs.docker.com/compose/faq/#why-do-my-services-take-10-seconds-to-recreate-or-stop

**Comment by uncaught** [comment]
Yes, your entrypoint (`servermanager.sh`) needs to delegate the shutdown to the services it starts.

I don't know where `PalServer.sh` comes from, but if that handles a shutdown signal (the docker stop signal can be adjusted), then maybe this could already do the trick:

```diff
-     ./PalServer.sh "$START_OPTIONS"
+    exec ./PalServer.sh "$START_OPTIONS"
```

`exec` will replace the top level process, so the signals go there now.

Not sure if you need your own process running still though.

**Comment by jammsen** [comment]
Hey @uncaught 
the PalServer.sh comes with the server, it sets some unreal-engine things.
PalServer.sh:
```
#!/bin/sh
UE_TRUE_SCRIPT_NAME=$(echo \"$0\" | xargs readlink -f)
UE_PROJECT_ROOT=$(dirname "$UE_TRUE_SCRIPT_NAME")
chmod +x "$UE_PROJECT_ROOT/Pal/Binaries/Linux/PalServer-Linux-Test"
"$UE_PROJECT_ROOT/Pal/Binaries/Linux/PalServer-Linux-Test" Pal "$@" 
```

But im working on a fix for that, a collegue of mine has something the might work and he was okay with me using it.

**Comment by uncaught** [comment]
3.3 seconds sounds good :)

**Comment by jammsen** [comment]
Please go ahead and test things.
New Docker-Compose File is needed.
You can find now examples in the README.md.
The docker-compose.yml was removed because of dublicate code.

**Comment by jammsen** [comment]
If this issue is solved, please give me feedback on the patch and please consider giving me a Star here and on Docker-Hub.

**Comment by jammsen** [comment]
@uncaught *Ping* please read the last 2 comments and tell me things

**Comment by jammsen** [comment]
Well its there binary and their shell-script, up to them to manage that beast, hehe 👍
