### ISSUE TITLE
trying to set bEnableInvaderEnemy=False

### ISSUE THREAD

**Issue by RSerejo** [jammsen/docker-palworld-dedicated-server#146]
### Have you read the Important information text above

- [X] Yes i did

### Describe the feature

i'm trying without sucess to set bEnableInvaderEnemy=False like a solution to memory leak.

### Additional information

- [ ] Would you be willing to help implement this feature?

### Final checks

- [X] I understand that this is a feature request function. I also unterstand that if i use this to report a bug report, that my issue might be un-answered closed.

**Comment by jammsen** [comment]
Hey @RSerejo set ENABLE_INVADER_ENEMY=false and next time create a bug-issue or you will not receive help.

Closed of wrong issue type
