### ISSUE TITLE
No content under palworld/game and cannot connect with server

### ISSUE THREAD

**Issue by xxzl0130** [jammsen/docker-palworld-dedicated-server#15]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

cannot see a `game/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini` file, Or to be precise, there's nothing in the `palworld/game` folder.

and also I cannot connect with this server.

### Desired behavior

The server is running and can be connected

### To Reproduce

I started the docker with the command below:

```
docker run --name palworld -p 8211 -e ALWAYS_UPDATE_ON_START=true -e MAX_PLAYERS=8 -e MULTITHREAD_ENABLED=true \
    -e COMMUNITY_SERVER=false -e PUBLIC_PORT=8211 -e PUBLIC_IP=43.139.150.139 -e SERVER_NAME=xworld \
    -e SERVER_DESCRIPTION="xx's pal world" -e SERVER_PASSWORD=xx233 -e ADMIN_PASSWORD=zaxs0130 \
    -v /home/ubuntu/palworld:/palworld \
    jammsen/palworld-dedicated-server
```

The log file has been uploaded to the attachment.
[docker.log](https://github.com/jammsen/docker-palworld-dedicated-server/files/14001493/7824d49583d914888627488ce4f5268116400e930514d960c9f0e7e290c20075-json.log)

### Software setup

- OS: Ubuntu22.04
- Docker: Docker version 24.0.7, build afdd53b

### Hardware setup

- vCPU: 2 core
- RAM: 8 GB
- Disk: 80 GB

**Comment by pierre-nicoli** [comment]
Have you created and tried chmod your palworld directory ?
```bash
# Supposing your home is indeed /home/ubuntu
mkdir /home/ubuntu/palword
chmod 777 /home/ubuntu/palworld
```

**Comment by xxzl0130** [comment]
> Have you created and tried chmod your palworld directory ?
> 
> ```shell
> # Supposing your home is indeed /home/ubuntu
> mkdir /home/ubuntu/palword
> chmod 777 /home/ubuntu/palworld
> ```

yes, I can see other folders and files like `Engine` or `linux64` inside the `palworld`, but only the `game` folder is empty

**Comment by kryst4line** [comment]
@xxzl0130  I had this too and the issue was that I had to create the palworld/game folder in advance and give it 777 permissions; after that it created all the files correctly

**Comment by CooperWallace** [comment]
@xxzl0130 You'll need to specify udp for the port, otherwise Docker defaults to tcp. Took me a bit to realize that myself

**Comment by jammsen** [comment]
Hey @xxzl0130 - If you use Docker 24.0.7 you should have access to docker-compose, you should use that, instead of very long docker-runs. Make sure your permissions/ownerships are correct, see the readme.

Hey @CooperWallace - That sounds familiar, do you have a Resource on this information for me please? I never found one.

**Comment by CooperWallace** [comment]
@jammsen Sure! Its on the top of this page, https://tech.palworldgame.com/dedicated-server-guide.

**Comment by CooperWallace** [comment]
@jammsen I just realized you probably meant the tcp part.
https://docs.docker.com/engine/reference/builder/#expose,
> By default, EXPOSE assumes TCP. You can also specify UDP:

**Comment by xxzl0130** [comment]
> Hey @xxzl0130 - If you use Docker 24.0.7 you should have access to docker-compose, you should use that, instead of very long docker-runs. Make sure your permissions/ownerships are correct, see the readme.
> 
> Hey @CooperWallace - That sounds familiar, do you have a Resource on this information for me please? I never found one.

I created the palworld/game folder in advance, and specify udp for the port, but there is still noting in palword/game folder.
<img width="343" alt="Snipaste_2024-01-22_11-07-07" src="https://github.com/jammsen/docker-palworld-dedicated-server/assets/9150038/37e79ce4-3492-42db-ae32-7573ecb8dc74">

And I noticed some error:

```
[S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
CAppInfoCacheReadFromDiskThread took 5 milliseconds to initialize
Setting breakpad minidump AppID = 2394010
[S_API FAIL] Tried to access Steam interface SteamUser021 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamFriends017 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface STEAMAPPS_INTERFACE_VERSION008 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.
```

**Comment by xxzl0130** [comment]
I realize I misunderstood things, the `palworld` folder corresponds to the `game` folder in readme, so now the problem is the `S_API FAIL` error.

**Comment by 906051999** [comment]
> I realize I misunderstood things, the `palworld` folder corresponds to the `game` folder in readme, so now the problem is the `S_API FAIL` error.我意识到我误解了一些事情， `palworld` 文件夹对应于自述文件中的 `game` 文件夹，所以现在的问题是 `S_API FAIL` 错误。

I'm in the same situation as you, this problem will be displayed after restarting the server, although I have queried some messages, and the task can ignore this error.
But I can't find my server in the social server.
```
[S_API FAIL] Tried to access Steam interface SteamUser021 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamFriends017 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface STEAMAPPS_INTERFACE_VERSION008 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.
```

**Comment by CooperWallace** [comment]
@xxzl0130 @906051999 Those are false positives and are always displayed. I run mine with those, and there's no isssues.

@906051999 As for the Server Browser, it looks like theres issues with too many servers. See if yours shows up in, https://www.battlemetrics.com/servers/palworld/.

**Comment by 906051999** [comment]
> @xxzl0130 @906051999 Those are false positives and are always displayed. I run mine with those, and there's no isssues. 这些都是假阳性，并始终显示。我用这些来运行我的，没有任何问题。
> 
> @906051999 As for the Server Browser, it looks like theres issues with too many servers. See if yours shows up in, https://www.battlemetrics.com/servers/palworld/. 至于服务器浏览器，看起来有太多服务器的问题。看看你的是否出现在https://www.battlemetrics.com/servers/palworld/中。

What ports do I need to open to my server to meet this business?
I tried opening 27015 and 8211

**Comment by xxzl0130** [comment]
> > @xxzl0130 @906051999 Those are false positives and are always displayed. I run mine with those, and there's no isssues. 这些都是假阳性，并始终显示。我用这些来运行我的，没有任何问题。
> > @906051999 As for the Server Browser, it looks like theres issues with too many servers. See if yours shows up in, https://www.battlemetrics.com/servers/palworld/. 至于服务器浏览器，看起来有太多服务器的问题。看看你的是否出现在[https://www.battlemetrics.com/servers/palworld/中。](https://www.battlemetrics.com/servers/palworld/%E4%B8%AD%E3%80%82)
> 
> What ports do I need to open to my server to meet this business? I tried opening 27015 and 8211

I think 27015 is useful.

And my friends can access to my server now, I think my home network meets some problem.

**Comment by xxzl0130** [comment]
UPD.

I cannot change the port, only 8211 can access.

thijsvanloef/palworld-server-docker can run correctly and can change port to others.

**Comment by 906051999** [comment]
> UPD.
> 
> I cannot change the port, only 8211 can access.
> 
> thijsvanloef/palworld-server-docker can run correctly and can change port to others.

I also used this project, and the IP direct connection was indeed successful, guessing that it was annotated with community-related configurations.
Actually, I just queried the server I tested earlier in the https://www.battlemetrics.com/servers/palworld/, but unfortunately the information update was delayed by an hour, maybe it was successful before, but I didn't wait.

**Comment by jammsen** [comment]
> UPD.
> 
> I cannot change the port, only 8211 can access.
> 
> thijsvanloef/palworld-server-docker can run correctly and can change port to others.

Hey @xxzl0130 - sure mine can this too. 8211 is only the internal port where the gameserver is publishing "Gamedata", you can just map this around with your Docker-Compose file in the ports section. But there are problems right now with the gameservers, see here https://tech.palworldgame.com/dedicated-server-guide#qa and according to Discord Announcment channel massive amounts of network-stress on Epic Online Service, so when your server just dont publish, try no-password and direct-connct via ip, like i do. The server-browser only gets 200 servers, you have to click so many times "next 200" that your gae sometimes breaks because of memory-leaks before you even can list you server. Thats just Early-Access, give them time to fix it.


> I realize I misunderstood things, the `palworld` folder corresponds to the `game` folder in readme, so now the problem is the `S_API FAIL` error.

Thoose are more like warnings, then errors, you can savely ignore them, a collegue of mine setup his docker-image in a different way and after the 2nd time it dis-appears, thats just Steam doing Steam things. most of others game do that too, according to him, so dont worry about that.

**Comment by xxzl0130** [comment]
> > UPD.
> > I cannot change the port, only 8211 can access.
> > thijsvanloef/palworld-server-docker can run correctly and can change port to others.
> 
> Hey @xxzl0130 - sure mine can this too. 8211 is only the internal port where the gameserver is publishing "Gamedata", you can just map this around with your Docker-Compose file in the ports section. But there are problems right now with the gameservers, see here https://tech.palworldgame.com/dedicated-server-guide#qa and according to Discord Announcment channel massive amounts of network-stress on Epic Online Service, so when your server just dont publish, try no-password and direct-connct via ip, like i do. The server-browser only gets 200 servers, you have to click so many times "next 200" that your gae sometimes breaks because of memory-leaks before you even can list you server. Thats just Early-Access, give them time to fix it.
> 
> > I realize I misunderstood things, the `palworld` folder corresponds to the `game` folder in readme, so now the problem is the `S_API FAIL` error.
> 
> Thoose are more like warnings, then errors, you can savely ignore them, a collegue of mine setup his docker-image in a different way and after the 2nd time it dis-appears, thats just Steam doing Steam things. most of others game do that too, according to him, so dont worry about that.

I changed the port setting through `PUBLIC_PORT`, and also I confirmed that the docker is listening on the desired port, but I just can't connect with it, it's wired. I'll try again later.

**Comment by jammsen** [comment]
Hey @xxzl0130 try reading from this comment and all of them below, maybe that helps you out:
https://github.com/jammsen/docker-palworld-dedicated-server/issues/9#issuecomment-1902786186

**Comment by xxzl0130** [comment]
The server is now working properly. I left my password blank and adjusted my local network to connect properly.

**Comment by jammsen** [comment]
Did the comments on the other pos help?

**Comment by xxzl0130** [comment]
It's mainly about password settings

**Comment by xxzl0130** [comment]
I also switched to Docker-Compose, which specifies the port as UDP, I don't know if this is different from using `docker run -p`, but it's easier to modify parameters

**Comment by jammsen** [comment]
Its much easier to define what the goal should be like and let docker-compose do the other stuff yes.
