### ISSUE TITLE
[Bug Report] When I set BUILD_OBJECT_DETERIORATION_DAMAGE_RATE, the PalAutoHpRegeneRateInSleep value is set the same value.

### ISSUE THREAD

**Issue by Deeeeepsleep** [jammsen/docker-palworld-dedicated-server#150]
### Have you read the Important information text above

- [x] Yes i did

### Current behavior

When I set BUILD_OBJECT_DETERIORATION_DAMAGE_RATE, the PalAutoHpRegeneRateInSleep value is set to the same value.

PAL_AUTO_HP_REGENE_RATE_IN_SLEEP=5.000000
BUILD_OBJECT_DETERIORATION_DAMAGE_RATE=0.000000

in defualt.env.

But in PalWorldSettings.ini
PalAutoHpRegeneRateInSleep=0.000000,BuildObjectDamageRate=0.000000,

### Desired behavior

Other env values set well.
only PAL_AUTO_HP_REGENE_RATE_IN_SLEEP value follow BUILD_OBJECT_DETERIORATION_DAMAGE_RATE value.

### Software setup

- OS: Ubuntu 20.04
- Docker: Docker Compose version v2.24.3

### Hardware setup

- vCPU: AMD Ryzen Threadripper 3990X
- RAM: 252GB
- Disk:

**Comment by tipanic** [comment]
The error was fixed, you should re-pull the latest image.

https://github.com/jammsen/docker-palworld-dedicated-server/issues/116
https://github.com/jammsen/docker-palworld-dedicated-server/pull/137

**Comment by jammsen** [comment]
Hey @Deeeeepsleep - @tipanic is right, please update your image and docker-compose default.env - We upgraded quite a lot yesterday to make it easier.

Im closing this issue as resolved, feel free to reach out again if you need help.

If you like this project, please consider giving this repo and the [docker-hub-repo](https://hub.docker.com/repository/docker/jammsen/palworld-dedicated-server) a Star.
