### ISSUE TITLE
[Feature Request] Multiple image repos and tagging

### ISSUE THREAD

**Issue by LilDrunkenSmurf** [jammsen/docker-palworld-dedicated-server#157]
### Have you read the Important information text above

- [X] Yes i did

### Describe the feature

Hi there!

Currently, I believe you're only pushing to dockerhub, and you're tagging with latest, master, develop, as well as the short SHA.

This is a two-part request, and more of a QoL for managing it, more than anything.

1) Would it be possible to also push to an alternative repo, like ghcr, or quay? This is for rate limiting.
2) Would it be possible to add semantic tagging to the image? Currently I like to pin to a specific version, instead of pulling latest and potentially getting breaking changes. I use renovate to bump images as PRs since everything is managed via git repo, but it doesn't know which commit to grab that would align with the version I'd want (latest? master?).

You can see how I manage it here:
https://github.com/LilDrunkenSmurf/k3s-home-cluster/blob/7a02ce9e25520b278976c23b2e047356448a97a2/kubernetes/teyvat/apps/games/palworld/app/helmrelease.yaml#L39

And this is a PR I have for a bump to use the new webhook functionality:
https://github.com/LilDrunkenSmurf/k3s-home-cluster/pull/1600

### Additional information

- [X] Would you be willing to help implement this feature?

### Final checks

- [X] I understand that this is a feature request function. I also unterstand that if i use this to report a bug report, that my issue might be un-answered closed.

**Comment by jammsen** [comment]
Hey @LilDrunkenSmurf 
Regarding 1. already doing that,  see here - https://github.com/jammsen/docker-palworld-dedicated-server/pkgs/container/docker-palworld-dedicated-server

Regarding 2. im totally lost on this topic, i have barely any knowledge about K3s or K8s yet, so i dont understand either what you want or mean. I can offer you a call on Discord so you can explain it to me.

**Comment by LilDrunkenSmurf** [comment]
Basically, tag the images with versions.
1.0.0
1.1.0
1.1.1
https://semver.org/

**Comment by jammsen** [comment]
@LilDrunkenSmurf Hello??!?

**Comment by LilDrunkenSmurf** [comment]
You're right, it worked great.

**Comment by jammsen** [comment]
Erm i asked you the questions here, please answer them:


> Would tags by date-day work too as an alternative? Like :2024-02-01 ?
> 
> Question: Why dont SHA-Hashes work? Does it get confused or what the pattern here?

I need an answer to be able to understand and improove things @LilDrunkenSmurf

**Comment by LilDrunkenSmurf** [comment]
SHA-hashes did work. I just have an aversion to pinning anything to latest, master, etc.

But Renovate did pick up the change: https://github.com/LilDrunkenSmurf/k3s-home-cluster/pull/1627

**Comment by jammsen** [comment]
Oh okay, gotcha, well im tagging tripple and dual:
Production: SHA7-Commit/master/latest
Development: SHA7-Commit/develop
https://github.com/jammsen/docker-palworld-dedicated-server/tree/develop/.github/workflows
Thanks for the FR

Im closing this issue as resolved, feel free to reach out again if you need help.

If you like this project, please consider giving this repo and the [Docker-Hub-Repo](https://hub.docker.com/repository/docker/jammsen/palworld-dedicated-server) a Star.
