### ISSUE TITLE
[Bug Report] ServerDescription is blank

### ISSUE THREAD

**Issue by arithxp** [jammsen/docker-palworld-dedicated-server#158]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

The server description set in default.env does not work.
`SERVER_DESCRIPTION=Exp,WorkSpd,DropItem,PalCap,EggHatch Modified
`

### Desired behavior

The server description must be recorded in the ini file.
However, the description is empty.
`ServerDescription=""`
![image](https://github.com/jammsen/docker-palworld-dedicated-server/assets/6009737/68a295da-f4f3-43bd-b5e9-f10f123a8787)

### Links to screenshots

cat default.env
![image](https://github.com/jammsen/docker-palworld-dedicated-server/assets/6009737/a5346cc6-6ba3-4249-bc71-2f35d1b9f5e6)

cat game/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini
![image](https://github.com/jammsen/docker-palworld-dedicated-server/assets/6009737/7405dba0-c741-4844-a041-f1625b276b9f)

### To Reproduce

1. download https://raw.githubusercontent.com/jammsen/docker-palworld-dedicated-server/develop/default.env
2. edit env file
3. docker-compose up -d
4. docker logs -f [docker name] or cat game/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini
5. blank ServerDescription

### Software setup

- OS: ubuntu 22.04 LTS
- Docker: Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1 | docker-compose version 1.29.2, build unknown

### Hardware setup

- vCPU: 4
- RAM: 24GB
- Disk: 15GB

### Additional context

There seem to be a few things wrong.
PLAYER_STOMACH_DECREASE_RATE (PLAYER_STOMACH_DECREACE_RATE)
BASE_CAMP_WORKER_MAXNUM (BASE_CAMP_WORKER_MAX_NUM maybe?)

docker logs
![image](https://github.com/jammsen/docker-palworld-dedicated-server/assets/6009737/319aa080-cc71-46eb-9304-fcc01ae6227b)

**Comment by arithxp** [comment]
I don't know why, but I tried it again and it worked.
It seems that the versions of the env file and the Docker server were different.
When I received a new env file, there was webhook content, but it was not in the env file I used. I deleted the env file, downloaded it again, and set it up, and it worked fine.

**Comment by jammsen** [comment]
Yeah we pushed a few updates, my just be that you had old cache of docker image.

Make sure to remove the image before and pull the newest version and check for changes in the docker-compose.yml and default.env file.

Changelog is coming, that might make things easier.

**Comment by jammsen** [comment]
Im closing this issue as resolved, feel free to reach out again if you need help.

If you like this project, please consider giving this repo and the [docker-hub-repo](https://hub.docker.com/repository/docker/jammsen/palworld-dedicated-server) a Star.

**Comment by arithxp** [comment]
> Im closing this issue as resolved, feel free to reach out again if you need help.
> 
> If you like this project, please consider giving this repo and the [docker-hub-repo](https://hub.docker.com/repository/docker/jammsen/palworld-dedicated-server) a Star.

I already clicked on the star. 😀

I have one question. Sorry for asking a question again on a closed issue.
When backing up, it is broadcasted and output twice.
![image](https://github.com/jammsen/docker-palworld-dedicated-server/assets/6009737/0d6d4d21-791f-4b24-b166-556d7514dc0d)
Are my settings wrong?
![image](https://github.com/jammsen/docker-palworld-dedicated-server/assets/6009737/792c3b62-c861-45d0-9e6f-1667f9441822)

**Comment by jammsen** [comment]
@arithxp  Thats an already known and fixed bug,  deployed to develop, will be later coming to master/prod/latest.
