### ISSUE TITLE
[Bug Report] Crashing server when using a mod

### ISSUE THREAD

**Issue by RSerejo** [jammsen/docker-palworld-dedicated-server#159]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

Server crash after add any mod on game client or game server

### Desired behavior

the game client just have some problem to join or not work fine if the mod is causing some problem.

### Links to screenshots

[log.txt](https://github.com/jammsen/docker-palworld-dedicated-server/files/14117539/log.txt)

### To Reproduce

try add some mod on the game what will joint the server, then remove the mod end try add some mod on game server.

### Software setup

- OS: Debian.
- Docker: last version using portainer.

### Hardware setup

R5 3600

### Additional context

i don`t know if it is the docker or the game server problem, but i think it is a good idea to report it.

**Comment by jammsen** [comment]
Im not sure if you are talking about the Client or Server or both, to have theese "mods".

I dont have one to test this, so you would need to link me your problem-child. The log of the server looks just fine.

Without any more information, i cant really help or test/try things in any way. 

Also please understand, im building an image to host the gameserver in a Docker-Way. Im not the support for the Game-Client nor the Game-Server. But if you give me way more information 😄 i might be able to test things.
