### ISSUE TITLE
Server Logging

### ISSUE THREAD

**Issue by JamesDConley** [jammsen/docker-palworld-dedicated-server#16]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

Currently when I launch the server I see the last logs as
```
[S_API FAIL] Tried to access Steam interface SteamUser021 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamFriends017 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface STEAMAPPS_INTERFACE_VERSION008 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded
```
Are there further logs available from Palsworld (ex. logins, chat, server status) that could be made available?
I've tried adding the "-log" to the base command in servermanager.sh but doesn't seem to have made much of a difference. I may need to rebuild, or maybe the logs are getting piped elsewhere, or worse don't exist?

### Desired behavior

Logs of server activity viewable with `docker logs [container name here]`

### To Reproduce

`docker compose up`
Connect to server and do stuff
View logs and see nothing has changed
or
 `docker logs [container name here]`
 and see nothing has been logged

### Software setup

- OS: 6.2.0-39-generic #40~22.04.1-Ubuntu
- Docker: Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1

### Hardware setup

- vCPU: 6 cores 12 threads (Ryzen 5 3600)
- RAM: 126GB RAM
- Disk: 17TB/32TB available (4-disk ZFS Pool, 2 data 1 parity one hot swap)

**Comment by jammsen** [comment]
Hey @JamesDConley - Sadly that is all the server gives out, i havent gotten anymore then you did in 2 days uptime on my own server where peope regularly play. Not 1 single line. I guess the server just isnt there yet. Keep in mind its still a Early-Access Version of the Game and the Dedicated-Server. Maybe down the line or in the roadmap we can get some little infos about more logging in the server.

**Comment by jammsen** [comment]
Can this issue be closed? @JamesDConley

**Comment by jammsen** [comment]
Closed because of inactivity
