### ISSUE TITLE
[Bug Report] Multiple backupmanager entries in supercronic cronlist.

### ISSUE THREAD

**Issue by SkylerGhostly** [jammsen/docker-palworld-dedicated-server#161]
### Have you read the Important information text above

- [x] Yes i did

### Current behavior

Occasionally, the `backupmanager.sh` script will be called again even if the `cronlist` file already contains a job. This causes the backup process to be called multiple times.

### Desired behavior

Backup operation should only execute once. 

### Links to screenshots

https://doe.wtf/6OhtWA
https://doe.wtf/0m2q_w

### To Reproduce

1. Compose & Start the image.
2. Use `docker compose restart`
3. `backupmanager.sh` adds another backup entry

### Software setup

- OS: Ubuntu 22.04.3 LTS
- Docker: Docker version 25.0.1, build 29cf629

### Hardware setup

- vCPU: AMD FX(tm)-8320 Eight-Core Processor, 4013 MHz
- RAM: 16 GB DDR3
- Disk: 120 GB Sata SSD (Crucial MX200)

**Comment by jammsen** [comment]
This bug should be gone when using docker-compose restart, im not touching now the file but writing it new. Feel free to test this and give me feedback on this.

If you like this project, please consider giving this repo and the [docker-hub-repo](https://hub.docker.com/repository/docker/jammsen/palworld-dedicated-server) a Star.

**Comment by SkylerGhostly** [comment]
Thanks for the quick fix. Much appreciated.

**Comment by jammsen** [comment]
> Thanks for the quick fix. Much appreciated.

No problem, please be aware its only on develop right now.

docker pull jammsen/palworld-dedicated-server:develop

I will merge later to prod/master/latest
