### ISSUE TITLE
[Feature Request] ARM version of the container

### ISSUE THREAD

**Issue by PaulMaersk** [jammsen/docker-palworld-dedicated-server#165]
### Have you read the Important information text above

- [X] Yes i did

### Describe the feature

Just wanted to know if it's possible to also support ARM architecture. Your containers are by far the best for hosting game servers.

### Additional information

- [X] Would you be willing to help implement this feature?

### Final checks

- [X] I understand that this is a feature request function. I also unterstand that if i use this to report a bug report, that my issue might be un-answered closed.

**Comment by PaulMaersk** [comment]
Wait, i see there was already one about this:
https://github.com/jammsen/docker-palworld-dedicated-server/issues/6

Closing feature request.

**Comment by jammsen** [comment]
Search-function the issues 👍
