### ISSUE TITLE
When SERVER_SETTINGS_MODE=manual ,  it's can't run

### ISSUE THREAD

**Issue by geekfrog** [jammsen/docker-palworld-dedicated-server#173]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

i set SERVER_SETTINGS_MODE “manual ”
it's shows 
2024-02-04 05:39:46 >>> Checking for existence of default credentials
2024-02-04 05:39:46 >>> Error: Security thread detected: Please change the default admin password. Aborting server start ...

### Desired behavior

docker run -d ^
--privileged=true ^
-e TZ="Asia/Shanghai" ^
-e ALWAYS_UPDATE_ON_START=true ^
-e MULTITHREAD_ENABLED=true ^
-e COMMUNITY_SERVER=true ^
-e BACKUP_ENABLED=true ^
-e BACKUP_CRON_EXPRESSION="0 * * * *" ^
-e BACKUP_RETENTION_POLICY=true ^
-e BACKUP_RETENTION_AMOUNT_TO_KEEP=150 ^
-e SERVER_SETTINGS_MODE=manual ^
-e STEAMCMD_VALIDATE_FILES=true ^
-p 8212:8212 ^
-p 8212:8212/udp ^
-p 25576:25576 ^
-v D:\DockerData\palworld2:/palworld ^
--name palworld2 ^
jammsen/palworld-dedicated-server

### To Reproduce

setSERVER_SETTINGS_MODE to “manual ”

### Software setup

- OS: 
- Docker:

### Hardware setup

- vCPU: 
- RAM: 
- Disk:

**Comment by sordidfellow** [comment]
Try setting these 2 environment variables that I pulled from https://github.com/jammsen/docker-palworld-dedicated-server/blob/develop/default.env

ADMIN_PASSWORD=adminPasswordHere
SERVER_PASSWORD=serverPasswordHere

**Comment by jammsen** [comment]
Hey @geekfrog - That Pre-Flight RPC check is for you not leaking that you use the default passwords and someone coming to your server, getting admin-login and kick/ban/restart it.
