### ISSUE TITLE
[Bug Report] change server port to other udp than 8211

### ISSUE THREAD

**Issue by chackl1990** [jammsen/docker-palworld-dedicated-server#177]
### Have you read the Important information text above

- [X] Yes i did, sorry if not

### Current behavior

Changing PUBLIC_PORT to anything in env file and correct it in compose file.
The game sees the server offline.

### Desired behavior

You need to set the following:
servermanager.sh:

Line: START_OPTIONS="-port=$PUBLIC_PORT"

Then it worked

### To Reproduce

1. Change PUBLIC_PORT in env file
2. Change port in docker-compose.yml
3. Start the server will lead the game to say that the server is offline / connection timeout.
4. Correct servermanager.sh may fix it.

### Software setup

- OS: Debian12
- Docker: not relevant

### Hardware setup

- vCPU: 4
- RAM: 32
- Disk: 50GB

### Additional context

Port Cmd-Line found here:
https://www.reddit.com/r/Palworld/comments/19b5byz/dedicated_server_not_letting_me_change_the_port/

**Comment by jammsen** [comment]
Hey @chackl1990 - The PUBLIC_PORT is for external usage (same as PUBLIC_IP) and telling the Master-Sever on how to connect to your server. You dont need to change the Port=8211, thats inside Docker, thats why you can change it in Docker-Compose. There is no bug here. Just setup your Docker-Compose and default.env the right way.

**Comment by chackl1990** [comment]
ok got it - i may have missed that sorry.
