### ISSUE TITLE
[Feature Request] Server restart without restarting container

### ISSUE THREAD

**Issue by thejcpalma** [jammsen/docker-palworld-dedicated-server#181]
### Have you read the Important information text above

- [X] Yes i did

### Describe the feature

Restart the server process to avoid memory leaks and reduce resource usage. 
Objectively to use in other scenarios like auto-restart, server auto-update, backup restore...

Feature is implemented, pending #179 

### Additional information

- [X] Would you be willing to help implement this feature?

### Final checks

- [X] I understand that this is a feature request function. I also unterstand that if i use this to report a bug report, that my issue might be un-answered closed.

**Comment by jammsen** [comment]
@thejcpalma Dublicate of #71
