### ISSUE TITLE
[Feature Request] Auto-update if no players connected

### ISSUE THREAD

**Issue by thejcpalma** [jammsen/docker-palworld-dedicated-server#183]
### Have you read the Important information text above

- [X] Yes i did

### Describe the feature

Auto update server when no players are connected (`X` amount of time between checks for version) . 
Willing to hear suggestions on this implementation.

Willing to implement this feature.

> [!WARNING] 
> Will only work when `RCON` is enabled, as it will need to fetch player info and the only way to obtain that currently is with `RCON`.

Depends on #181 

### Additional information

- [X] Would you be willing to help implement this feature?

### Final checks

- [X] I understand that this is a feature request function. I also unterstand that if i use this to report a bug report, that my issue might be un-answered closed.

**Comment by jammsen** [comment]
Dublicate of #51 please close this, we only need to gather information once.
