### ISSUE TITLE
[Bug Report] Please redact sensitive information from the logs

### ISSUE THREAD

**Issue by mindflay3r** [jammsen/docker-palworld-dedicated-server#194]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

These fields shouldn't be logged: https://github.com/jammsen/docker-palworld-dedicated-server/blob/bb8e0a1fcda6737e69b80513d6270499974461fa/includes/config.sh#L268-L275

### Desired behavior

They should instead say `[REDACTED]` or not be included at all.

### To Reproduce

n/a

### Software setup

n/a

### Hardware setup

n/a

### Additional context

Someone posted their creds here: https://github.com/jammsen/docker-palworld-dedicated-server/issues/193

**Comment by mickgriddle** [comment]
I think that as more users use this docker image it will be beneficial to redact these fields. I think palworld will bring a lot of newer people to docker who could easily give their details away. I support redacting the info.
