### ISSUE TITLE
[Feature Request] More details in logs

### ISSUE THREAD

**Issue by Geekmeleon** [jammsen/docker-palworld-dedicated-server#200]
### Have you read the Important information text above

- [X] Yes i did

### Describe the feature

Not sure if it is the Palworld Server logging that is not detailed enough, or the container not grabbing everything from the server logs.  I would like to see connection attempts, log in and log outs, console commands, etc.. in the docker logs section

### Additional information

- [ ] Would you be willing to help implement this feature?

### Final checks

- [X] I understand that this is a feature request function. I also understand that if i use this to report a bug report, that my issue might be un-answered closed.

**Comment by jammsen** [comment]
Hey @Geekmeleon - Me too, the server doesnt log ANYTHING except the start and on Exit, thats it. Nothing i can do about that.

**Comment by Geekmeleon** [comment]
Sounds good!   Thanks for responding.

**Comment by jammsen** [comment]
Im closing this issue as resolved, feel free to reach out again if you need help.

If you like this project, please consider giving this repo and the [Docker-Hub-Repo](https://hub.docker.com/repository/docker/jammsen/palworld-dedicated-server) a Star.
