### ISSUE TITLE
[Bug Report] Different CPU usage information.

### ISSUE THREAD

**Issue by TFidk** [jammsen/docker-palworld-dedicated-server#206]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

I installed the Palworld Server on a Synology NAS and it is running. Sometimes there are / were lags and then I checked the utilization of the RAM and the CPU. When it comes to the CPU, I noticed that when I look up the utilization directly on the container, the utilization is completely different than what is displayed in parallel in the resource monitor of the NAS system. Which information is correct? According to the container, the CPU utilization is often over 100%. Makes no sense.

<img width="1070" alt="Palworld_Server_CPU-Usage" src="https://github.com/jammsen/docker-palworld-dedicated-server/assets/91210035/91796685-d011-4610-baaf-698015228a18">

### Desired behavior

Ideally, the utilization information matches in order to have precise information about the utilization.

### To Reproduce

1. Go to "Container Manager" in the Synology NAS
2. Click on 'Project'
3. Right-Click on Palworld-Server
4. Choose "Detail"
5. Then the container utilization is displayed

### Software setup

- Synology DSM 7.2x
- Docker: latest Container Manager 20.10.23-1437

### Hardware setup

- CPU: Intel Pentium N3710 Quad-Core 1,6 GHz, Turbo up to 2,56 GHz
- RAM: 16GB DDR3
- Disk: 20TB

**Comment by jammsen** [comment]
Hey @TFidk - Not sure about the inner mechanics on your NAS and i cant support that, BUT it looks to me that your "Container-Manager" uses Docker's Stat tool and that lists still 120% CPU-Usage for me too, when i use 30% on 4 threads. The Ressource-Monitor" seems to show multi-threads and general load usage on multiple threads. So its a difference in toolings that gets confusing for you together i guess?

**Comment by jammsen** [comment]
Im closing this issue as resolved, feel free to reach out again if you need help.

If you like this project, please consider giving this repo and the [Docker-Hub-Repo](https://hub.docker.com/repository/docker/jammsen/palworld-dedicated-server) a Star.
