### ISSUE TITLE
[Feature Request] Setting to not show in-game backup broadcast message

### ISSUE THREAD

**Issue by Krojack** [jammsen/docker-palworld-dedicated-server#208]
### Have you read the Important information text above

- [X] Yes i did

### Describe the feature

I would like a way to disable this.

I have edited the script in the past then also mounted it via volume `- ./backupmanager.sh:/backupmanager.sh` but with the latest changes and it moving to the /scripts directory, I just figured a setting to just not have it broadcast in the .env file would be a better option.

### Additional information

- [ ] Would you be willing to help implement this feature?

### Final checks

- [X] I understand that this is a feature request function. I also understand that if i use this to report a bug report, that my issue might be un-answered closed.

**Comment by jammsen** [comment]
Hey @Krojack - That setting already exists, its called RCON_ENABLED

**Comment by Krojack** [comment]
I thought that turned the entire rcon system on or off. I still use rcon at the command line for other things as well such as the ShowUsers.

**Comment by jammsen** [comment]
So what you actually asking for is a feature-toggle to not broadcast anything while the server makes backups or saves?
How would the user know on when to expect maybe lag or robberbanding?

**Comment by Callum027** [comment]
> So what you actually asking for is a feature-toggle to not broadcast anything while the server makes backups or saves? How would the user know on when to expect maybe lag or robberbanding?

I think the OP does not consider it necessary to alert the user in this case.

From a personal perspective, I haven't had any lag or rubberbanding as a result of the background job running, it's very quick (but my instance is running on NVMe SSDs).

**Comment by jammsen** [comment]
> I think the OP does not consider it necessary to alert the user in this case.
> 
> From a personal perspective, I haven't had any lag or rubberbanding as a result of the background job running, it's very quick (but my instance is running on NVMe SSDs).

SSD is only part of the calculation, CPU and RAM Speed matter too, we had also rubberbanding with busy or old and slow (GHz) CPUs reportet or even very slow DDR4 (2133MHz, forgot to turn on XMP) RAM.

**Comment by Krojack** [comment]
Yeah I haven't experienced any lag or anything while the backup is running. I wasn't even aware it was a problem as it was so fast and smooth.

With 5-6 players my CPU averages around 10%. I even mount the /palworld/backups directly to a directory on my NAS so the backups are saved there rather than local.

For now this is my docker volumes setup:
```
    volumes:
      - ./game-data:/palworld
      - ./steam-logs:/home/steam/Steam/logs
      - /mnt/nas_backups/GameServer/palworld/backups:/palworld/backups
      - ./backupmanager.sh:/scripts/backupmanager.sh
```
I'm able to just comment out the parts of the backup script which is fine, I just though an option to not show the in-game backup alerts would be a nice option people can set in the .env file.
