### ISSUE TITLE
[Bug Report] After one suddenly crash, the server keeps crashing

### ISSUE THREAD

**Issue by Hellfirest** [jammsen/docker-palworld-dedicated-server#210]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

Last night, my server meets a server crash my friends told me, this is the first crash report

[Pal-CRC-backup-2024.02.18-13.06.07.log](https://github.com/jammsen/docker-palworld-dedicated-server/files/14325315/Pal-CRC-backup-2024.02.18-13.06.07.log)

This morning I reboot my synology nas server for maintainance, and then suddenly the server keeps on crash, this is the latest crash report

[Pal-CRC-backup-2024.02.19-00.57.20.log](https://github.com/jammsen/docker-palworld-dedicated-server/files/14325321/Pal-CRC-backup-2024.02.19-00.57.20.log)

### Desired behavior

Pleas help me to identify the crash reason and method to fix it

### To Reproduce

Dont know how to reproduce the problem

### Software setup

- OS: Synology 6.2.3
- Docker: latest pull

### Hardware setup

- vCPU:  9500t
- RAM:  32G ddr4 2666mhz
- Disk: 8 HC550 16T

**Comment by Hellfirest** [comment]
![屏幕截图 2024-02-19 093600](https://github.com/jammsen/docker-palworld-dedicated-server/assets/96698184/5f3c8f19-e152-436d-9ed9-c0260c131ec0)
this is log from synology docker

**Comment by Hellfirest** [comment]
i restore saved files from nearest backup files and problem solved, it seemed that the saved file crashed, but cant figure out where since at that moment it was my friends played and no clue what had they done

**Comment by jammsen** [comment]
Hey @Hellfirest - Glad it works again, thanks for sharing the resolution!

**Comment by Hellfirest** [comment]
Hey @jammsen  thanks for this amazing docker. And I may find the reason of this problem

Synology provide a gui crontab to maintain server and I write a script to check memory usage every 30min, if palworld server exceed 16G then rcon save, broadcast to my friend, and restart docker

In the new version of pds you provide backupmanager that I didnt notice, default env setting backup server every hour. So the crash maybe at the sametime my script conflict with backupmanager

Now I changed BACKUP_CRON_EXPRESSION to 5 5 * * * to avoid two policy working at the same time

Will see if any furthuer crash would happen

parts of my script is as follows:


if (( $(awk -v gb="$memory_usage_gb" 'BEGIN { printf (gb > 16) }') )); then
    echo "Memory usage exceeds 16GB. Sending broadcast and saving world before restarting..."

    # using mcron to broadcast danger message, save, restart
    mcrcon -H $mcrcon_ip -P $mcrcon_port -p $mcrcon_password "broadcast Memory_usage_exceeds_16GB_Server_will_restart_soon_Actual_memory_usage:" 
    mcrcon -H $mcrcon_ip -P $mcrcon_port -p $mcrcon_password "broadcast $memory_usage_gb GB"


    # use mcrcon save
    mcrcon -H $mcrcon_ip -P $mcrcon_port -p $mcrcon_password "save"

    echo "Broadcast sent and world saved."
    sleep 10
    # restart 
    echo "Restarting docker instance..."
    docker restart jammsen-palworld-dedicated-server1
    echo "Docker instance restarted."
else
   mcrcon -H $mcrcon_ip -P $mcrcon_port -p $mcrcon_password "broadcast Memory_usage_fine_Actual_memory_usage:"
   mcrcon -H $mcrcon_ip -P $mcrcon_port -p $mcrcon_password "broadcast $memory_usage_gb"
    echo "Memory usage within acceptable limits."
