### ISSUE TITLE
[Bug Report] Updated container now doesnt start

### ISSUE THREAD

**Issue by ashmaker000** [jammsen/docker-palworld-dedicated-server#213]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

Starting updated docker now shows below after pulling the latest docker image:

![image](https://github.com/jammsen/docker-palworld-dedicated-server/assets/8276382/7d0f6f38-ac61-46b5-be44-c20dfd46abfa)

Have already disabled webhooks and still behaves the 

### Desired behavior

Palworld to load

### Software setup

- OS: Linux
- Docker:

### Hardware setup

- vCPU: 
- RAM: 
- Disk:

**Comment by jammsen** [comment]
Hey @ashmaker000 - You post an error with no context, no hardware, no software and your description just stops mid-sentence ... Do you acutally want help? How do you expect me to help you .... ???
