### ISSUE TITLE
[Bug Report] Player Join/Leave if steam name has spaces breaks message

### ISSUE THREAD

**Issue by Krojack** [jammsen/docker-palworld-dedicated-server#224]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

rcon broadcast stops after the blank space in name.

### Desired behavior

To display the entire name and rest of the message

### To Reproduce

no real steps, just wait for someone to join/leave that has a space in their steam name.

### Software setup

- OS: Linux
- Docker: 

### Hardware setup

- vCPU: 
- RAM: 
- Disk:

### Additional context

Not 100% sure what script is processing this but I found the following.

I modified the /includes/rcon.sh script for the join/leave functions..

Added this to replace spaces with an underscore
`PLAYER=$(sed 's/ /_/g' <<< "$1")`

Modified
`rconcli "broadcast ${time}-Player-${PLAYER}-has-left-the-server"`

This should work but I haven't seen my friend join to test yet.

**Comment by Dashboy1998** [comment]
I made a PR for this. Instead of using sed I used [GUN Shell Parameter Expansion](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html)
```
rconcli "broadcast ${time}-Player-${1// /-}-has-joined-the-server"
```

**Comment by Krojack** [comment]
Still doesn't seem to be working after I updated this morning.

![image](https://github.com/jammsen/docker-palworld-dedicated-server/assets/908461/d0863274-444e-4f55-9a26-a78e82e9f159)

**Comment by jammsen** [comment]
> Still doesn't seem to be working after I updated this morning. The one with "Lapin" has a blank space in the name.
> 
> ![image](https://private-user-images.githubusercontent.com/908461/307397941-d0863274-444e-4f55-9a26-a78e82e9f159.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MDkzNDUsIm5iZiI6MTcwODcwOTA0NSwicGF0aCI6Ii85MDg0NjEvMzA3Mzk3OTQxLWQwODYzMjc0LTQ0NGUtNGY1NS05YTI2LWE3OGU4MmU5ZjE1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QxNzI0MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTMxMWJiZjg4MTg1NWIxODZhYjJmOGE0MjNmYjEyYmIyZTRiNTNjMTU0ODc3YTg1OWYxMjVmNzdiZWExMDA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KRaXLxM33LXEmmwI11FF3bmy-vdZsfegl5E5ji668GI)
> 
> On a side note that I wouldn't worry about, that person is also Alastrim. I'm not sure why it shows 2 times. They show as that name on my Steam friends and their profile. The Lapin part I don't see anywhere. Not sure what Steam is doing there.

This is only on develop image tag for now, when i release this, i create an annoucement in Discord.

Im working an various edge-cases like special characters and that sort of things right now.
