### ISSUE TITLE
[Bug Report] Player join/left issue with character creation

### ISSUE THREAD

**Issue by Dashboy1998** [jammsen/docker-palworld-dedicated-server#226]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

By default when you join a game and while in player creation your player name is your steam name.
If you choose a different name then join/left says your steam name left and your player name joined

```
palworld-dedicated-server  | > RCON: Broadcasted: 14:39:53-Player-Dashboy1998-has-joined-the-server
palworld-dedicated-server  | 14:40:53: Player Foobar has joined the server.
palworld-dedicated-server  | > RCON: Broadcasted: 14:40:53-Player-Foobar-has-joined-the-server
palworld-dedicated-server  | 14:40:53: Player Dashboy1998 has left the server.
palworld-dedicated-server  | > RCON: Broadcasted: 14:40:53-Player-Dashboy1998-has-left-the-server
```

### Desired behavior

Either wait for the player to be created or announce a name change.
```
palworld-dedicated-server  | > RCON: Broadcasted: 14:39:53-Player-Dashboy1998-has-joined-the-server
palworld-dedicated-server  | > RCON: Broadcasted: 14:40:53-Player-Dashboy1998-has-changed-his-name-to-Foobar
```

### To Reproduce

1. Join a game in which you do not have a character
2. Wait in creation menu until the server logs you have joined
3. Create character with a different name than your steam name

### Software setup

N/A

### Hardware setup

N/A

**Comment by jammsen** [comment]
Fixed that and its now more steamid oriented
