### ISSUE TITLE
[Bug Report] Player join/leave cannot have commas in name

### ISSUE THREAD

**Issue by Dashboy1998** [jammsen/docker-palworld-dedicated-server#227]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

If you have a comma in your name then only the part before the comma is shown when you join/leave.
When I create a character whose name is `Dash,boy1998` then I get the following `palworld-dedicated-server  | 04:13:10: Player Dash has joined the server.`

### Desired behavior

Should be showing the entire name so when I create a character whose name is `Dash,boy1998` then I should get the following `palworld-dedicated-server  | 04:13:10: Player Dash,boy1998 has joined the server.`

### To Reproduce

1. Create a character whose name contains a comma
2. View join/leave log

### Software setup

N/A

### Hardware setup

N/A

**Comment by jammsen** [comment]
Fixed that and also striped all chars execept [a-zA-Z0-9]
