### ISSUE TITLE
[Bug Report] Player join/leave doesn't work with players of the same name

### ISSUE THREAD

**Issue by Dashboy1998** [jammsen/docker-palworld-dedicated-server#228]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

When multiple players with the same name are playing then join is only logged for the first player to join and left is only logged for the last player to leave.

### Desired behavior

Should be announcing when each player joins/leaves. 

### To Reproduce

1. Create a server with no save
2. Join and create your character
3. Have someone else join and them use the same name as you
4. Wait for RCON_PLAYER_DETECTION_CHECK_INTERVAL
5. Have one player leave and Wait for RCON_PLAYER_DETECTION_CHECK_INTERVAL
6. Have second player leave

### Software setup

N/A

### Hardware setup

N/A

### Additional context

Being completely honest I can't remember if it's possible or not for two players to have the same name. Pretty sure I tried this and got that result when I was making my PR. However it was a late night so don't remember 100%.

**Comment by jammsen** [comment]
This should also be fixed, its more steamid oriented now.
