### ISSUE TITLE
[Bug Report] RCON Port setting change in 1.50

### ISSUE THREAD

**Issue by robertlane** [jammsen/docker-palworld-dedicated-server#236]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

PocketPair has updated the server, and they have moved how the RCON port setting is handled. The setting is now run from the start options. Currently this means RCON functionality is broken if the server is updated.

### Desired behavior

RCON is not opened on port specified.

### To Reproduce

Restart or recreate image
Allow steam to update server
Attempt to connect with RCON or view log faults

### Software setup

- OS: Debian 12
- Docker: 25.03

### Hardware setup

- vCPU: i5 3rd gen
- RAM: 16gb

**Comment by Jadiction** [comment]
@jammsen The fix for this is to add "-RCONPort=25575" to the startup arguments in [server.sh](https://github.com/jammsen/docker-palworld-dedicated-server/blob/develop/includes/server.sh) (I haven't tested this, but I see a lot of mentions of it)

Another thing I see mentioned is that you now need "-publiclobby" to have your server show up on the community servers list.

**Comment by Jadiction** [comment]
Also, not to get off topic; but additionally to the update, there is now a server setting - `bShowPlayerList=True`. You'll want to add this to the server settings ENVs.

**Comment by robertlane** [comment]
I have the rcon option added to server.sh and mounted over the image. This works and allows the internal scripts to launch. I saw the player list option as well. I'll have to catch up on all the changes tomorrow.

**Comment by jammsen** [comment]
Testing develop branch in my root-dedicated right now and writing up release-notes.

**Comment by jammsen** [comment]
LGTM - everything is working fine, except that when you are on a mount with a name and someone open the playerlist the name of the mount is used for the players, but i cant do anything on that!

**Comment by jammsen** [comment]
Discord Release message is out, build is on latest. This should be all fixed. Manual in how to update is in the releaes channel in Discord. 

Im closing this issue as resolved, feel free to reach out again if you need help.

If you like this project, please consider giving this repo and the [Docker-Hub-Repo](https://hub.docker.com/repository/docker/jammsen/palworld-dedicated-server) a Star.
