### ISSUE TITLE
[Bug Report] Error when auto restart

### ISSUE THREAD

**Issue by wayne1203** [jammsen/docker-palworld-dedicated-server#237]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

Added RESTART_ENABLED=true and RESTART_CRON_EXPRESSION=0 5 * * * in YAML. Cron job is running on time but got error

2024/02/27 05:00:00 | stderr | time="2024-02-27T05:00:00+08:00" level=error msg="error running command: exit status 1" iteration=0 job.command=restart job.position=1 job.schedule="0 5 * * *"
-- | -- | --
2024/02/27 05:00:00 | stderr | /usr/local/bin/restart: line 12: PLAYER_DETECTION.PID: No such file or directory

</body>
</html>

### Desired behavior

Will auto restart at 5am

### To Reproduce

Setting RESTART_ENABLED=true and RESTART_CRON_EXPRESSION=0 5 * * * and wait when 5

### Software setup

- OS: DSM 7.2 (Synology)
- Docker: 20.10.23

### Hardware setup

DS918+
- CPU: INTEL Celeron J3455 1.5Ghz
- RAM: 16GB
- Disk: 5.4GB (RAID)

### Additional context

It's work in the first version added auto restart cron function, after that no working anymore.

**Comment by jammsen** [comment]
Hey @wayne1203 - Try a new and fresh install, new and fresh docker-compose and default.env with the latest image please.

**Comment by WayneTvT** [comment]
Thanks @jammsen . Fixed with updated new default.env
I'll remember to update the file after any update.

**Comment by jammsen** [comment]
Well @wayne1203 - If you are in Discord and have listed the releases channel i even explain by release what you have to change, you just need to follow that, less merge problems that way.

BUT happy it works 😎 

Im closing this issue as resolved, feel free to reach out again if you need help or join the Discord to chat directly.

If you like this project, please consider giving this repo and the [Docker-Hub-Repo](https://hub.docker.com/repository/docker/jammsen/palworld-dedicated-server) a Star.
