### ISSUE TITLE
docker部署后无法正常使用RCON，cli: execute: auth: rcon: dial tcp: lookup tcp/###RCON_PORT###:unknown port

### ISSUE THREAD

**Issue by islift** [jammsen/docker-palworld-dedicated-server#245]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

docker重新部署后，启动容器后正常运行，但是会提示 cli: execute: auth: rcon: dial tcp: lookup tcp/###RCON_PORT###:unknown port
另外无法修改基地内部的帕鲁数量，被固定在了15个，修改docker环境项BASE_CAMP_WORKER跟PalWorldSettings.ini并没有改变基地的帕鲁数量
![QQ截图20240305124743](https://github.com/jammsen/docker-palworld-dedicated-server/assets/81837182/0e633aa4-c404-458c-8da9-ab1340775ae0)

### Desired behavior

希望能正常使用RCON

### To Reproduce

部署后已删除webhook

### Software setup

[/Script/Pal.PalGameWorldSettings]
OptionSettings=(Difficulty=Difficulty,DayTimeSpeedRate=1.200000,NightTimeSpeedRate=1.200000,ExpRate=2.000000,PalCaptureRate=3.999999,PalSpawnNumRate=2.000000,PalDamageRateAttack=1.000000,PalDamageRateDefense=1.000000,PlayerDamageRateAttack=2.000000,PlayerDamageRateDefense=1.000000,PlayerStomachDecreaceRate=1.000000,PlayerStaminaDecreaceRate=0.001000,PlayerAutoHPRegeneRate=2.000000,PlayerAutoHpRegeneRateInSleep=2.000000,PalStomachDecreaceRate=1.000000,PalStaminaDecreaceRate=0.001000,PalAutoHPRegeneRate=2.000000,PalAutoHpRegeneRateInSleep=2.000000,BuildObjectDamageRate=1.000000,BuildObjectDeteriorationDamageRate=1.000000,CollectionDropRate=2.999999,CollectionObjectHpRate=1.000000,CollectionObjectRespawnSpeedRate=4.000000,EnemyDropItemRate=2.999999,DeathPenalty=None,bEnablePlayerToPlayerDamage=False,bEnableFriendlyFire=False,bEnableInvaderEnemy=True,bActiveUNKO=False,bEnableAimAssistPad=True,bEnableAimAssistKeyboard=False,DropItemMaxNum=3000,DropItemMaxNum_UNKO=100,BaseCampMaxNum=128,BaseCampWorkerMaxNum=20,DropItemAliveMaxHours=1.000000,bAutoResetGuildNoOnlinePlayers=False,AutoResetGuildTimeNoOnlinePlayers=72.000000,GuildPlayerMaxNum=40,PalEggDefaultHatchingTime=0.000000,WorkSpeedRate=2.000000,bIsMultiplay=False,bIsPvP=False,bCanPickupOtherGuildDeathPenaltyDrop=False,bEnableNonLoginPenalty=True,bEnableFastTravel=True,bIsStartLocationSelectByMap=True,bExistPlayerAfterLogout=False,bEnableDefenseOtherGuildPlayer=False,CoopPlayerMaxNum=4,ServerPlayerMaxNum=120,ServerName="星星",ServerDescription="wopingwojiaoao",AdminPassword=xingxingA--,ServerPassword=xingxing158,PublicPort=8211,PublicIP="",RCONEnabled=true,RCONPort=25575,Region="",bUseAuth=True,BanListURL="https://api.palworldgame.com/api/banlist.txt")

### Hardware setup

G4600T+32G内存

**Comment by jammsen** [comment]
> After docker is redeployed, the container runs normally after starting it, but it will prompt cli: execute: auth: rcon: dial tcp: lookup tcp/###RCON_PORT###:unknown port In addition

Yes that is why you can setup the times for the PLAYER_DETECTION, do it right and you will never see the message pop up

> ... the number of palus inside the base cannot be modified and is fixed at 15. Modifying the docker environment items BASE_CAMP_WORKER and PalWorldSettings.ini does not change the number of palus in the base.

This is a known limitation of the game and is even explained in the FAQ (we have the code ready for setting configs, for when they fix this finally):
https://github.com/jammsen/docker-palworld-dedicated-server?tab=readme-ov-file#i-changed-the-basecampworkermaxnum-setting-why-didnt-this-update-the-server

**Comment by islift** [comment]
感谢您的回复，上面的回复已经收到，已确认基地无法修改人数这个问题，关于目前的RCON端口我如上的设置但是通过容器 jokerwho-palworld-server-tool 尝试访问时，对方并不能访问到25575端口 
2024/03/05-04:58:22|ERROR | task/task.go:42 | rcon: dial tcp 172.17.0.1:25575: connect:connection refused
烦请问下这种情况是属于正常的吗，再次感谢您的支持

**Comment by jammsen** [comment]
You have to wait until the server is done starting, when you see thoose 4 lines here, the server is done starting:

```
palworld-dedicated-server  | [S_API FAIL] Tried to access Steam interface SteamUser021 before SteamAPI_Init succeeded.
palworld-dedicated-server  | [S_API FAIL] Tried to access Steam interface SteamFriends017 before SteamAPI_Init succeeded.
palworld-dedicated-server  | [S_API FAIL] Tried to access Steam interface STEAMAPPS_INTERFACE_VERSION008 before SteamAPI_Init succeeded.
palworld-dedicated-server  | [S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.
```

For using RCON, you need to pull the latest image (Why? Because Pocketpair did break some things about rcon fairly recently) and setup the RCON Env-Vars like you want and like the Docu is explaining it.

If you still have a problem, then try a clean/fresh install with new docker-compose and fresh default.env and see if that works.

**Comment by islift** [comment]
感谢您，解决了我好几天都没有解决的问题，非常感谢您的支撑，他很有帮助，真的非常感谢。

发件人: Sebastian Schmidt ***@***.***>
发送时间: 2024年3月5日 23:37
收件人: jammsen/docker-palworld-dedicated-server ***@***.***>
抄送: islift ***@***.***>; Author ***@***.***>
主题: Re: [jammsen/docker-palworld-dedicated-server] docker部署后无法正常使用RCON，cli: execute: auth: rcon: dial tcp: lookup tcp/###RCON_PORT###:unknown port (Issue #245)


You have to wait until the server is done starting, when you see thoose 4 lines here, the server is done starting:

palworld-dedicated-server  | [S_API FAIL] Tried to access Steam interface SteamUser021 before SteamAPI_Init succeeded.

palworld-dedicated-server  | [S_API FAIL] Tried to access Steam interface SteamFriends017 before SteamAPI_Init succeeded.

palworld-dedicated-server  | [S_API FAIL] Tried to access Steam interface STEAMAPPS_INTERFACE_VERSION008 before SteamAPI_Init succeeded.

palworld-dedicated-server  | [S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.

For using RCON, you need to pull the latest image (Why? Because Pocketpair did break some things about rcon fairly recently) and setup the RCON Env-Vars like you want and like the Docu is explaining it.

If you still have a problem, then try a clean/fresh install with new docker-compose and fresh default.env and see if that works.

**Comment by jammsen** [comment]
Happy that helped.

**Comment by jammsen** [comment]
Im closing this issue as resolved, feel free to reach out again if you need help or join the Discord to chat directly.

If you like this project, please consider giving this repo and the [Docker-Hub-Repo](https://hub.docker.com/repository/docker/jammsen/palworld-dedicated-server) a Star.
