### ISSUE TITLE
Container crashes with error: Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by lsahnicne** [jammsen/docker-palworld-dedicated-server#25]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

Server crashes with the following text in logs:
Illegal instruction (core dumped)

### Desired behavior

Server runs properly

### To Reproduce

1. Pull the image with 

> docker pull jammsen/palworld-dedicated-server

2. Creater docker-compose file with the following contents:

> version: '3.9'
> services:
>   palworld-dedicated-server:
>     build: .
>     container_name: palworldserver
>     image: jammsen/palworld-dedicated-server:latest
>     restart: unless-stopped
>     network_mode: bridge
>     ports:
>       - target: 8211 # gamerserver port inside of the container
>         published: 8211 # gamerserver port on your host
>         protocol: udp
>         mode: host
>       - target: 25575 # rcon port inside of the container
>         published: 25575 # rcon port on your host
>         protocol: tcp
>         mode: host
>     environment:
>       - ALWAYS_UPDATE_ON_START=true
>       - MAX_PLAYERS=32
>       - MULTITHREAD_ENABLED=true
>       - COMMUNITY_SERVER=false
>       - RCON_ENABLED=false
>       - RCON_PORT=25575
>       - PUBLIC_IP=1.2.3.4
>       - PUBLIC_PORT=8211
>       - SERVER_NAME=servername
>       - SERVER_DESCRIPTION=server
>       - SERVER_PASSWORD=xxxxxxxxxxx
>       - ADMIN_PASSWORD=xxxxxxxx
>     volumes:
>       #- ./game:/palworld
>       - /srv/palworld:/palworld
>   
>   rcon:
>     image: outdead/rcon:latest
>     entrypoint: ['/rcon', '-a', '10.0.0.5:25575', '-p', 'adminPasswordHere']
>     profiles: ['rcon']

4. Up the dockerfile
5. Wait for downloads to complete
6. Container keeps restarting with the following messages in logs:

> Connecting anonymously to Steam Public...OK
> Waiting for client config...OK
> Waiting for user info...OK
>  Update state (0x5) verifying install, progress: 0.00 (0 / 4729437191)
>  Update state (0x5) verifying install, progress: 4.59 (217113154 / 4729437191)
>  Update state (0x5) verifying install, progress: 14.85 (702350583 / 4729437191)
>  Update state (0x5) verifying install, progress: 25.43 (1202528046 / 4729437191)
>  Update state (0x5) verifying install, progress: 34.03 (1609375534 / 4729437191)
>  Update state (0x5) verifying install, progress: 44.90 (2123466873 / 4729437191)
>  Update state (0x5) verifying install, progress: 55.95 (2646093743 / 4729437191)
>  Update state (0x5) verifying install, progress: 66.20 (3130910237 / 4729437191)
>  Update state (0x5) verifying install, progress: 76.51 (3618301150 / 4729437191)
>  Update state (0x5) verifying install, progress: 85.61 (4048669143 / 4729437191)
>  Update state (0x5) verifying install, progress: 96.78 (4577164587 / 4729437191)
> Success! App '2394010' fully installed.
> `>>> Starting the gameserver`
> Checking if config exists
> Setting rcon-enabled to false
> Setting rcon-port to 25575
> Setting public ip to 1.2.3.4
> Setting public port to 8211
> Setting server name to servername
> Setting server description to server
> Setting server password to xxxxxxxxxxx
> Setting server admin password to xxxxxxxx
> Setting max-players to 32
> Illegal instruction (core dumped)

### Software setup

- OS: OpenMediaVault 6.3.2-2
- Docker: 20.10.23

### Hardware setup

- CPU: AMD Phenom(tm) II X4 965 Processor 
- RAM: 23.39 GiB
- Disk: 358,12 GiB free

**Comment by jammsen** [comment]
Hey @lsahnicne 
was this version of the container working before?
Is this a fresh install?
What are the permission on the "game" directory?

**Comment by jbettencourt10** [comment]
Just out of curiosity, how much ram are you running with? I believe I was having this error because my server has 8 gb of ram (some being used by other services, so actually less), and Palworld at minimum requires 8gb of ram I believe.

**Comment by lsahnicne** [comment]
> Hey @lsahnicne was this version of the container working before? Is this a fresh install? What are the permission on the "game" directory?

No,

**Comment by jammsen** [comment]
Hey @lsahnicne 
"Does it NEED to be named "game"?" No not really but i have to use a known term, for you to understand what im talking about and the "game" directory should be known if you read my readme.
Fresh install of Docker no, i meant fresh install of the latest docker-compose file and the latest docker-image.

**Comment by ComputersWithTimo** [comment]
@lsahnicne make sure the permissions are set up correctly.
As a test, u could `chmod 777 /srv/palworld`.

I had a similar issue when I was moving Hosts on Podman (because of memory restrictions).
The server did start, but immediately crashed once a player connected because it wasn't able to write to its folder.


P.s. u can run a small server on just 4GB of RAM, but it will get laggy quickly.

**Comment by lsahnicne** [comment]
Issue identified thanks to the duplicate #41 - I have the exact same CPU and it appears to simply be too old to run this game's server :(
