### ISSUE TITLE
[Feature Request] Implement server OoM crash detection and restart

### ISSUE THREAD

**Issue by jchoo44** [jammsen/docker-palworld-dedicated-server#250]
### Have you read the Important information text above

- [X] Yes i did

### Describe the feature

As mentioned in this fix for the memory leak in Pal Linux dedicated server,
[Reddit-PalworldAdmin-SelfRestarting](https://www.reddit.com/r/PalServerAdmin/comments/1azzg7r/self_logging_restarting_potential_workaround)/,
Would it be possible to add these changes to the Docker image?

### Additional information

- [x] Would you be willing to help implement this feature?

### Final checks

- [X] I understand that this is a feature request function. I also understand that if i use this to report a bug report, that my issue might be un-answered closed.

**Comment by jammsen** [comment]
Hey @jchoo44 - This is sort of implemented with the restart-cron that you can setup to fit your needs and your individual setup.

**Comment by jchoo44** [comment]
Thank you, I'll use your solution. My server is up to 25GB with the leak.
