### ISSUE TITLE
[Bug Report] Container backups also backup the Palworld built-in backups

### ISSUE THREAD

**Issue by Callum027** [jammsen/docker-palworld-dedicated-server#257]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

https://tech.palworldgame.com/settings-and-operation/configuration#about-bisusebackupsavedata

From Palworld v0.2.0.6, a backup feature is built-in, where it backs up data to a `backup` folder in the game data folder.

```
root@palworld1:~# ls -l /opt/palworld-dedicated-server/data/Pal/Saved/SaveGames/0/0452330FBC4D438F803678C2A6C04043
total 10568
-rw-r--r-- 1 palworld palworld 10806094 Apr  6 02:18 Level.sav
-rw-r--r-- 1 palworld palworld     1557 Apr  6 02:18 LevelMeta.sav
drwxr-xr-x 2 palworld palworld     4096 Apr  6 02:18 Players
drwxr-xr-x 3 palworld palworld     4096 Apr  4 07:37 backup
```

This `backup` folder is being included with our container-based backups, expontially increasing the size of the backups.

```
root@palworld1:/opt/palworld-dedicated-server/data/backups# ls -lh | grep 20240404 | head -n1
-rw-r--r-- 1 palworld palworld  19M Apr  3 11:00 saved-20240404_000000.tar.gz
root@palworld1:/opt/palworld-dedicated-server/data/backups# ls -lh | grep 20240405 | tail -n1
-rw-r--r-- 1 palworld palworld 219M Apr  5 10:01 saved-20240405_230000.tar.gz
```

This is made worse by the fact that the latest version of the container enables **both** backup methods by default (`BACKUP_ENABLED` and `ENABLE_WORLD_BACKUP` are both set to `true`).

### Desired behavior

I recommend we:

* Disable one of the two backup methods by default. I recommend disabling the Palworld built-in one by default, as it is less configurable than the container's backup options.
* Make sure that even if `bIsUseBackupSaveData` is enabled, there is no problem, by excluding those backups from the container-based backups by adding `--exclude=backup` to the `tar` command.

### To Reproduce

1. Start the container with the default backup options
2. Let the server run for a while
3. Observe the container backup files quick increase in file size

### Software setup

- OS: Ubuntu 22.04 LTS
- Docker: 26.0.0

### Hardware setup

- vCPU: 4 vCPU
- RAM: 16GB
- Disk: 10GB OS volume, 10GB Palworld OS volume (both NVMe at 1000 IOPS)

**Comment by jammsen** [comment]
As discussed in DC - Internal backup mechanic is now off by default.
