### ISSUE TITLE
[Bug Report] Automatic Restart stopped working

### ISSUE THREAD

**Issue by jchoo44** [jammsen/docker-palworld-dedicated-server#263]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

When the automatic restart cron task is executed, the script fails with the following.
```
>>> Automatic restart was triggered...
/usr/local/bin/restart: line 16: PLAYER_DETECTION.PID: No such file or directory
```

### Desired behavior

Server should restart

### To Reproduce

Enable Env Variables:
RESTART_CRON_EXPRESSION | 0 12 * * *
RESTART_DEBUG_OVERRIDE | false
RESTART_ENABLED | true

### Software setup

- OS: Debian 12 - Linux 6.1.0-18
- Docker: 20.10.24

### Hardware setup

- vCPU: 
- RAM: 
- Disk:

**Comment by jammsen** [comment]
Hey @jchoo44 
Please check if all this conditions are set:
https://github.com/jammsen/docker-palworld-dedicated-server/blob/af721cd4f8fa1e010d41d198ec6f8a4b26d6e7b5/scripts/servermanager.sh#L56

Talking about the IF statement around the echo.
