### ISSUE TITLE
[Question]  您好，我在游戏中，会接受到容器显示的备份 通知，我想询问下这个备份通知能否不在游戏内显示，可以在容器日志中

### ISSUE THREAD

**Issue by islift** [jammsen/docker-palworld-dedicated-server#265]
### Have you read the Important information text above

- [X] Yes i did

### Describe the feature

您好，我在游戏中，会接受到容器显示的备份通知，我想询问下这个备份通知能否不在游戏内显示，可以在容器日志中，
![QQ截图20240430194701](https://github.com/jammsen/docker-palworld-dedicated-server/assets/81837182/13d218b0-997c-4c4c-b494-6726f2c593fc)

### Additional information

- [X] Would you be willing to help implement this feature?

### Final checks

- [X] I understand that this is a feature request function. I also understand that if i use this to report a bug report, that my issue might be un-answered closed.

**Comment by jammsen** [comment]
Hey @islift 
No either you have this and all notifications, or you turn rcon off and loose all others too.

**Comment by islift** [comment]
已收到，感谢您的解答，谢谢

发件人: Sebastian Schmidt ***@***.***>
发送时间: 2024年4月30日 21:42
收件人: jammsen/docker-palworld-dedicated-server ***@***.***>
抄送: islift ***@***.***>; Mention ***@***.***>
主题: Re: [jammsen/docker-palworld-dedicated-server] [Feature Request] 您好，我在游戏中，会接受到容器显示的备份 通知，我想询问下这个备份通知能否不在游戏内显示，可以在容器日志中 (Issue #265)


Hey @islift<https://github.com/islift>
No either you have this and all notifications, or you turn rcon off and loose all others too.

**Comment by jammsen** [comment]
Closed because of inactivity
