### ISSUE TITLE
[Bug Report] No config found, generating one

### ISSUE THREAD

**Issue by YuZongYangHi** [jammsen/docker-palworld-dedicated-server#267]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

I am trying to switch from the Windows environment to the Linux Docker environment. The data directory Saved has been migrated to the new environment. However, after starting it, I found that it cannot find the Config directory. I checked that the data storage directory exists.

![image](https://github.com/jammsen/docker-palworld-dedicated-server/assets/35584408/accbe481-d82d-4140-8f57-27b6114b8f9e)

![image](https://github.com/jammsen/docker-palworld-dedicated-server/assets/35584408/9b00f869-1a10-437f-81ca-9a22d3e3a677)

### Desired behavior

Normally the check should pass, why not?

### Software setup

- OS:
- Docker:

### Hardware setup

- vCPU: 
- RAM: 
- Disk:

**Comment by jammsen** [comment]
Hey @YuZongYangHi - Looks like you permissions are wonky, try to create a fresh install under with my image without any data in there before and compare to it.

Also ich have no clue what youre trying to say here
> Desired behavior
> Normally the check should pass, why not?

Its as follows, you deliver me some needed informations on your setup and your problem and i/we try to help you. If you fail to provide that, thats on you and to expect anyone to help you out.

**Comment by YuZongYangHi** [comment]
It should be a permissions issue, I solved it, thank you

**Comment by jammsen** [comment]
Hey @YuZongYangHi - Happy to hear that.
Also sorry if my last message came over a bit rough, didnt mean to do that. I rephrased it now what i had in my mind for that.
Sorry.
