### ISSUE TITLE
Add healthcheck to the dockerfile

### ISSUE THREAD

**Issue by Seneschul** [jammsen/docker-palworld-dedicated-server#275]
### Have you read the Important information text above

- [X] Yes i did

### Describe the feature

Docker has the ability to check the health of a dockerfile, and if the dockerfile fails this healthcheck too many times, docker can restart the dockerfile.
https://docs.docker.com/reference/dockerfile/#healthcheck
I would have suggested using "docker exec palworld-dedicated-server rconcli info" as the basis, but I am given to understand that this suggestion is subpar, as rconcli can have it's own issues, compounding the overall problem.
e.g. my suggested command is probably a bad idea.

Another channel member suggested strongly that using ps may be a better solution to the issue of the palworld dockerfile getting hung up, which makes more sense.

### Additional information

- [ ] Would you be willing to help implement this feature?

### Final checks

- [X] I understand that this is a feature request function. I also understand that if i use this to report a bug report, that my issue might be un-answered closed.

**Comment by jammsen** [comment]
There are a few ways to solve this, but using an protocol that might not react to requests or might be spammed isnt my favorite because of the high chance of false positives.

I will look into this next weekend, im busy right now.

**Comment by jammsen** [comment]
Added this, based on process lookups. Pushing this to master in the next minutes.
