### ISSUE TITLE
[Feature Request] Add instructions / capabilities for importing existing saves

### ISSUE THREAD

**Issue by anton-dealmeida** [jammsen/docker-palworld-dedicated-server#278]
### Have you read the Important information text above

- [X] Yes i did

### Describe the feature

Is it possible to mount in existing saves and configurations? Could we perhaps add that capability for people to for example bring an existing save that may have started locally for funsies into a more dedicated scene via volume mounts with some instructions around this?

### Additional information

- [X] Would you be willing to help implement this feature?

### Final checks

- [X] I understand that this is a feature request function. I also understand that if i use this to report a bug report, that my issue might be un-answered closed.

**Comment by jammsen** [comment]
Hey @anton-dealmeida im just replacing whats in my backup file with the original directory, what do you in mind as a "guide"? Maybe im not seeying the bigger picture here, do we need this?

**Comment by anton-dealmeida** [comment]
Hi @jammsen, so - a lot of people start playing co-op and host it that way. It would be really handy and draw a lot more use of this if people were, for example given the option to import their existing save and world which brings across their world. The tricky part though is the host character is usually lost so I'm guessing incorporating the host-character migration processes that are out there for the saves.

Not truly necessary but a really nice to have

**Comment by jammsen** [comment]
Hey @anton-dealmeida - But you do realize this is a Docker-Image around a Dedicated Server right? This is not a "Server-Migration-Tool", you would have to cover Windows to Linux gamesaves, edge-cases that come with everys scenario and all that kind of stuff, i dont really see, how this "Migration-Tool", wouldn't be its own tool and would break the context of what i try to solve with this Docker-Image  (Host in a good way with a lot of flexibility PalworldDS).

Again im open for a good and descriptive FAQ entry PR that explains on what to do, or if another tool exists for this to add a link to that tool in an FAQ entry, but i think this topic has so many potential that it is, its own thing, or am i not seeing something here?

**Comment by anton-dealmeida** [comment]
Sorry, you're right - I'm being a potato in explaining myself here.

I think just a good FAQ would be handy along with perhaps just suggestions around which volume paths to mount to host to ensure saves are kept or saves can be pulled in successfully.

**Comment by jammsen** [comment]
@anton-dealmeida - If you are missing something or have a good source to refer to, im open to look into it. Feel free to send me some links to that.
