### ISSUE TITLE
[Feature Request] Add ENV Support for server config setting SupplyDropSpan

### ISSUE THREAD

**Issue by KyleDiao** [jammsen/docker-palworld-dedicated-server#279]
### Have you read the Important information text above

- [X] Yes i did

### Describe the feature

Add ENV Support for server config setting SupplyDropSpan[=180] which control Interval for supply drop (minutes)

refer:  https://tech.palworldgame.com/settings-and-operation/configuration/

### Additional information

- [X] Would you be willing to help implement this feature?

### Final checks

- [X] I understand that this is a feature request function. I also understand that if i use this to report a bug report, that my issue might be un-answered closed.

**Comment by JuleNissen** [comment]
I though I was doing something wrong. I was under the impression that we could add this as an env-var ourselves and it would be applied. But during start of docker and server this variable get ignored from env file and default value (180) set.

I am not familiar enough with docker-setup and such, but I believe the variable support should be more dynamic as we do not know how many variables will be implemented in the future or even rename. If possible.

**Comment by KyleDiao** [comment]
> I though I was doing something wrong. I was under the impression that we could add this as an env-var ourselves and it would be applied. But during start of docker and server this variable get ignored from env file and default value (180) set.
> 
> I am not familiar enough with docker-setup and such, but I believe the variable support should be more dynamic as we do not know how many variables will be implemented in the future or even rename. If possible.

if u can edit your own container content(exec into it), u can refer to the PR  #280, both edit tmpl and config.sh can make the env take effect

**Comment by jammsen** [comment]
> I though I was doing something wrong. I was under the impression that we could add this as an env-var ourselves and it would be applied. But during start of docker and server this variable get ignored from env file and default value (180) set.

Hey @JuleNissen  - Well if you go manual config mode yes, if not and you want to control it via Docker, then you need to have a script that takes a value and places a value where you want it, its not automagically 👍 😎 

@KyleDiao did already a PR, its missing only 1 thing then im happy to merge it.

**Comment by jammsen** [comment]
Feel free to test this in about 5 minutes at the `jammsen/palworld-dedicated-server:develop` tag.
Feedback ist welcome so it can be merged after extendsive testing to master/live/prod.

**Comment by Krojack** [comment]
Any progress been made on this? I've tried adding SUPPLY_DROP_SPAN to my .env and it doesn't register.

**Comment by jammsen** [comment]
> Any progress been made on this? I've tried adding SUPPLY_DROP_SPAN to my .env and it doesn't register.

Thats because its on the :develop docker image tag.

I can merge it to master/live/prod/latest on the weekend

**Comment by jammsen** [comment]
Its now on master, have fun playing!
