### ISSUE TITLE
Question about methods for configuration

### ISSUE THREAD

**Issue by kof8855** [jammsen/docker-palworld-dedicated-server#29]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

Why, after modifying the PalWorldSettings.ini configuration and restarting the Docker container, does the PalWorldSettings.ini configuration revert to the default settings? I don't want to use variable methods for configuration.

### Desired behavior

Why, after modifying the PalWorldSettings.ini configuration and restarting the Docker container, does the PalWorldSettings.ini configuration revert to the default settings? I don't want to use variable methods for configuration.

### To Reproduce

Why, after modifying the PalWorldSettings.ini configuration and restarting the Docker container, does the PalWorldSettings.ini configuration revert to the default settings? I don't want to use variable methods for configuration.

### Software setup

Why, after modifying the PalWorldSettings.ini configuration and restarting the Docker container, does the PalWorldSettings.ini configuration revert to the default settings? I don't want to use variable methods for configuration.

### Hardware setup

Why, after modifying the PalWorldSettings.ini configuration and restarting the Docker container, does the PalWorldSettings.ini configuration revert to the default settings? I don't want to use variable methods for configuration.

**Comment by jammsen** [comment]
Hello @kof8855 
Because its considered Best-Practice in Docker and Docker-Compose to have your application not do that.
Its called Stateless-Development with some tools, see here: https://12factor.net/config
