### ISSUE TITLE
Add queryport for community server

### ISSUE THREAD

**Issue by Reymouth** [jammsen/docker-palworld-dedicated-server#35]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

The server is not visible in the list of community servers. The variable is set to COMMUNITY_SERVER=true

### Desired behavior

Added the -queryport=XXX option to the command line, if the variable is configured and can customize the port

### To Reproduce

Start the server with the variable COMMUNITY_SERVER=true. The server is not visible

### Software setup

- OS: Debian 12
- Docker: Docker 25.0.0

### Hardware setup

- vCPU: 8
- RAM: 64G
- Disk: 500G

**Comment by jammsen** [comment]
Hey @Reymouth, the port thingy is implemented als described here https://github.com/jammsen/docker-palworld-dedicated-server?tab=readme-ov-file#environment-variables - Your other problem that you cant see the server in the Community-Server-Tab is down to Pocketpair und EOS (Epic Online Services) to fix, there is almost nothing i can do there. The game is so popular that it broke multiple time EOS in the last days. Try using Community yes, Password none and direct connect via ip. That works just fine and almost everyone does this, right now, until the bugs get fixed from the Dev-Studio.

**Comment by Reymouth** [comment]
I tried several combinations. I created an issue, as many people have fixed this with the --queryport=27015 option and exposes it.

This option is different from the port reserved for RCON

**Comment by jammsen** [comment]
Can you like me some sources to look into that please? Thanks

**Comment by ComputersWithTimo** [comment]
> I tried several combinations. I created an issue, as many people have fixed this with the --queryport=27015 option and exposes it.
> 
> This option is different from the port reserved for RCON

Iirc the queryport 27015 is commonly used by the steamworks sdk.
Palworld uses EOS though.

According to the PalWorld Docs there is currently no "QueryPort" option:
https://tech.palworldgame.com/community-server-guide


Also:
My Server is visible in the Community Server List, with just the game port being opened.

If you have problems finding your server in the community server list, please read the Q&A at the bottom of this page:
https://tech.palworldgame.com/community-server-guide

Once players have connected to the server, it's easier to find as it will appear further up on the list.

**Comment by jammsen** [comment]
> Once players have connected to the server, it's easier to find as it will appear further up on the list.

It appears under "Recent Server". @ComputersWithTimo Thanks for confirming, i had the same informations.

Im closing this issue as resolved, feel free reopen again if needed.

If you like this project, please consider giving this repo and the docker-hub-repo a Star.
