### ISSUE TITLE
Fatal Error: Steamcmd needs to be online to update

### ISSUE THREAD

**Issue by karthrand** [jammsen/docker-palworld-dedicated-server#37]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

1.docker compose up -d
2.docker logs  palworld-dedicated-server

error：
 >>> Doing a fresh install of the gameserver
time="2024-01-23T17:08:05Z" level=info msg="read crontab: cronlist"
tid(17) burning pthread_key_t == 0 so we never use it
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Logging directory: '/home/steam/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
[  0%] Downloading update...
[  0%] Checking for available updates...
[----] !!! Fatal Error: Steamcmd needs to be online to update. Please confirm your network connection and try again.
src/tier0/threadtools.cpp (3706) : Assertion Failed: Illegal termination of worker thread 'Thread(0x0x570fbad0/0x0xf7732b'
 
i can not finish the install step

### Desired behavior

none

### Software setup

- OS: centos
- Docker: 24.0.7

### Hardware setup

- vCPU: 4c
- RAM: 14g
- Disk: 1t

**Comment by jammsen** [comment]
Hey @karthrand steamcmd is a package manager that downloads files from the internet, if it has no connection, then you should check your network/nat/firewall settings.

**Comment by karthrand** [comment]
yes,you are right,after add http proxy and https proxy
It's working properly now.

**Comment by Kaydax** [comment]
This is still happening, steamcmd can update fine on the host but fails to update when ran inside of docker

**Comment by jammsen** [comment]
Happy i could be of help.

If this issue is resolved, please close it and consider giving this repo and the docker-hub-repo a star.

**Comment by TombSte** [comment]
> add http proxy and https proxy

Hey, how do you solved? I have the same issue

**Comment by jammsen** [comment]
> Hey, how do you solved? I have the same issue

See:


> yes,you are right,after add http proxy and https proxy
> It's working properly now.

Im closing this issue as resolved, feel free to try it out and reopen again if needed.

If you like this project, please consider giving this repo and the docker-hub-repo a Star.

**Comment by karthrand** [comment]
> > add http proxy and https proxy
> 
> Hey, how do you solved? I have the same issue

yes，
add proxy in the host and
the container

**Comment by axxis-creator** [comment]
Hello i need help. What you mean with add proxy can you explane it plaease. 

`root@47b2a9480994:~# steamcmd
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[  0%] Checking for available update...
CreateBoundSocket: failed to create socket, error [no name available] (38)
[----] Verifying installation...
[  0%] Downloading Update...
[  0%] Checking for available update...
CreateBoundSocket: failed to create socket, error [no name available] (38)
[----] !!! Fatal Error: Steamcmd needs to be online to update.   Please confirm your network connection and try again.
threadtools.cpp (3294) : Assertion Failed: Illegal termination of worker thread 'Thread(0x0x573f6b30/0x0xf7bdfb'`

**Comment by Daxolion** [comment]
https://github.com/moby/moby/releases/tag/docker-v29.4.3


this is an issue on Docker 29.4.2 and has been fixed in new versions.

**Comment by jammsen** [comment]
@Daxolion Please dont Necro years old issues, thanks!
