### ISSUE TITLE
Add an Environment Option for bEnableNonLoginPenalty

### ISSUE THREAD

**Issue by Zer0mis** [jammsen/docker-palworld-dedicated-server#38]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

At the moment as discussed in a few open issues, the config file gets updated every time you start the server, so it loses custom configs for game settings you might want to change. 

In this case I want to be able to disable bEnableNonLoginPenalty in PalWorldSettings.ini because as far as I understand, this is the option which causes all your Pals to be depressed, injured or whatever else when you first log in on the server every day. Which at the moment seems incredibly opressive, and annoying.

### Desired behavior

An option to be able to set the setting inside the environmental options so it persists through restarts. 

### To Reproduce

n/a

### Software setup

n/a

### Hardware setup

n/a

**Comment by jammsen** [comment]
Hey @Zer0mis - Please have a look at #40

**Comment by Zer0mis** [comment]
Great news, looking forward to it being implemented!

**Comment by jammsen** [comment]
Sorry for the big delay .... 😭 

This issue should be solved with the commit and release from earlier today.

You can find it here https://github.com/jammsen/docker-palworld-dedicated-server/commit/8546c890a518c99ab9be13b35a876c01ddaa7bde#diff-3b41cd2eeb76ac64c4b71b9cc6b253b358ab737f50d54e333b631ca27357e98e 

Im closing this issue as resolved, feel free to try it out and reopen again if needed.

If you like this project, please consider giving this repo and the docker-hub-repo a Star.
