### ISSUE TITLE
Double slashes with $GAME_PATH

### ISSUE THREAD

**Issue by MalTeeez** [jammsen/docker-palworld-dedicated-server#4]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

The script tries to read /palworld//Pal/ since $GAME_PATH has a trailing slash.

### Desired behavior

The script should read /palworld/Pal/

### To Reproduce

 Run the servermanager.sh script

### Software setup

- Newest script with a689ffe35d12
- Debian
- Docker Compose

### Hardware setup

- Docker containerd virtualized hardware

**Comment by jammsen** [comment]
Thanks for reporting, its fixed and will be released soon, im testing right now, feel free to contribute in #1 and maybe help me test 😄

**Comment by MalTeeez** [comment]
Jup I'm available, still via github, or maybe discord?

**Comment by jammsen** [comment]
My Discord name is jammsen too.
