### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by CleryMenuel** [jammsen/docker-palworld-dedicated-server#41]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

When I start the container it restarts every 20 seconds.

### Desired behavior

DOCKER LOG:
Loading Steam API...OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x5) verifying install, progress: 0.00 (0 / 4729437191)
 Update state (0x5) verifying install, progress: 7.45 (352381458 / 4729437191)
 Update state (0x5) verifying install, progress: 19.68 (930940151 / 4729437191)
 Update state (0x5) verifying install, progress: 31.92 (1509760814 / 4729437191)
 Update state (0x5) verifying install, progress: 44.09 (2085244037 / 4729437191)
 Update state (0x5) verifying install, progress: 56.47 (2670757946 / 4729437191)
 Update state (0x5) verifying install, progress: 68.71 (3249510552 / 4729437191)
 Update state (0x5) verifying install, progress: 81.02 (3831594787 / 4729437191)
 Update state (0x5) verifying install, progress: 93.06 (4401165458 / 4729437191)
Success! App '2394010' fully installed.
>>> Starting the gameserver
Checking if config exists
Setting rcon-enabled to true
Setting rcon-port to 25575
Setting public ip to  ****
Setting public port to 49154
Setting server name to ****
Setting server description to Palworld-Dedicated-Server running in Docker by jammsen
Setting server password to *****
Setting server admin password to *****
Setting max-players to 32
Illegal instruction (core dumped)
>>> Doing an update of the gameserver
tid(12) burning pthread_key_t == 0 so we never use it
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Logging directory: '/home/steam/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1705108307
-- type 'quit' to exit --

compose.yml:

version: '2.24.0'
services:
  palworld-dedicated-server:
    #build: .
    container_name: palworld-dedicated-server
    image: jammsen/palworld-dedicated-server:latest
    restart: always
    network_mode: bridge
    ports:
      - target: 49154 # gamerserver port inside of the container
        published: 49154 # gamerserver port on your host
        protocol: udp
        mode: host
      - target: 25575 # rcon port inside of the container
        published: 25575 # rcon port on your host
        protocol: tcp
        mode: host
    environment:
      - ALWAYS_UPDATE_ON_START=true
      - MAX_PLAYERS=32
      - MULTITHREAD_ENABLED=true
      - COMMUNITY_SERVER=true
      - RCON_ENABLED=true
      - RCON_PORT=25575
      - PUBLIC_IP= ****
      - PUBLIC_PORT=49154
      - SERVER_NAME=****
      - SERVER_DESCRIPTION=Palworld-Dedicated-Server running in Docker by jammsen
      - SERVER_PASSWORD=****
      - ADMIN_PASSWORD=****
      - BACKUP_ENABLED=true
      - BACKUP_CRON_EXPRESSION=0 * * * *
    volumes:
      - ./game:/palworld

### Software setup

- OS: Debian 12
- Docker: docker compose version 2.24.0

### Hardware setup

- vCPU: 
- RAM: 16go
- Disk:256 go

**Comment by jammsen** [comment]
Hey @CleryMenuel check your RAM, looks like your OOM killer is active.

**Comment by CleryMenuel** [comment]
I tried disabling OOM killer by putting 2 to the /proc/sys/vm/overcommit_memory file to disable it but it doesn't seem to work the same problem even when restarting it
![Capture d'écran 2024-01-23 212430](https://github.com/jammsen/docker-palworld-dedicated-server/assets/91963215/0a3c2869-bdf1-4280-bc13-d955a97fc554)

**Comment by kotori** [comment]
I believe this is not related to memory settings at all, but instead related to CPU instructions that are not available on older CPU models. Example Ref: https://steamcommunity.com/app/677620/discussions/0/2957166487939172506/
My debugging of the PalServer.sh script shows pretty similar results, along with the illegal instruction crash.

**Comment by CleryMenuel** [comment]
yes my CPU is quite old, here I am finding an excuse to reinstall my whole system I will install the container on an Intel Core i5 4440. If you don't see me again, it's because I managed to reinstall the container and it's working.

**Comment by jammsen** [comment]
> yes my CPU is quite old, here I am finding an excuse to reinstall my whole system I will install the container on an Intel Core i5 4440. If you don't see me again, it's because I managed to reinstall the container and it's working.
> 
> UPDATE: After changing the CPU, I don't get the error.

Happy to hear that! Have fun playing!
