### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by CleryMenuel** [jammsen/docker-palworld-dedicated-server#46]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

mon container demarre correctement mais mon server n'apparait pas sur le jeu et e n'arrive pas a me connecter meme avec l'adresse IP publique IP_PUBLIC:PORT
I opened my ports on my router port 49154/UDP. Do I also need to open port 25575? If so, can I change the port? It's been done before and it wasn't working.

### Desired behavior

Docker Compose version v2.24.0-birthday.10

### Links to screenshots

docker logs 
![Capture d'écran 2024-01-24 041553](https://github.com/jammsen/docker-palworld-dedicated-server/assets/91963215/751ba25a-65d5-4ce2-81db-6c24d695c467)

compose.yml:
![Capture d'écran 2024-01-24 041852](https://github.com/jammsen/docker-palworld-dedicated-server/assets/91963215/1ca6d8d7-ca7a-4022-80d7-490216a36419)

### Software setup

- OS: Debian 12
- Docker: 2.24.0

### Hardware setup

- vCPU: 
- RAM: 16
- Disk:258

**Comment by ComputersWithTimo** [comment]
@CleryMenuel No, you don't need to forward 25575.
Do you get the "no password has been entered" error? 

Or does it not connect at all?
Do you even have a public IPv4?
(this sounds like a home connection and here in Germany a lot of ISPs run a 4to6 tunnel)

To debug, you might need to run a tcpdump on the host.
Something like this should work:
`tcpdump -i ens192 udp port 49154`

**Comment by CleryMenuel** [comment]
I get a timed connection when I try to log in No request from Passwword

For my part, my other services still use IPv4 as a public IP address (I come from France)

![Capture d'écran 2024-01-24 124228](https://github.com/jammsen/docker-palworld-dedicated-server/assets/91963215/ebc61fe8-2bb0-4109-bc1e-35d4bef13ca4)
I get when trying to log in on Palworld 192.168.1.254 matches my router 192.168.1.60 is the IP address of my server My game is indeed a Steam version

**Comment by lordimac** [comment]
You cant enter a password when connection to an ip. This is a known bug in Palworld and not from this container. Workaround is trying to connect to another server with password, enter the password and on connection screen say no. Then connect to ip.

**Comment by CleryMenuel** [comment]
it's works thanks a lot
