### ISSUE TITLE
PalEggDefaultHatchingTime resets to 72 every time restarting container

### ISSUE THREAD

**Issue by Sungjin-Wie** [jammsen/docker-palworld-dedicated-server#47]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

PalEggDefaultHatchingTime resets to 72 every time starting container.

### Desired behavior

want to set PalEggDefaultHatchingTime in Pal/Saved/Config/LinuxServer/PalWorldSettings.ini

### Links to screenshots
![image](https://github.com/jammsen/docker-palworld-dedicated-server/assets/49471767/05547f5a-54de-494c-a0a8-fa68ddbdf651)

### To Reproduce

1. Go to Pal/Saved/Config/LinuxServer/
2. Open PalWorldSettings.ini
3. Set PalEggDefaultHatchingTime to other value and restart container
4. Open PalWorldSettings.ini again and you can see 72.000000 again

### Software setup

- OS: Linux version 5.4.0-169-generic (buildd@lcy02-amd64-102) (gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.2)) #187-Ubuntu SMP Thu Nov 23 14:52:28 UTC 2023
(on Hyper-V)
- Docker: Docker version 24.0.5, build 24.0.5-0ubuntu1~20.04.1

### Hardware setup

- vCPU: 8
- RAM: 32GB
- Disk: 128GB virtual disk

### Additional context

I've tried 0.000000, 1.000000, 0, everything didn't work and PalEggDefaultHatchingTime resets to 72.000000 when initializing server.
setting DeathPenalty=None works. (DeathPenalty value persists when restarting container)

**Comment by Sungjin-Wie** [comment]
changes applies when I set value **AFTER** stopping container, sorry.

**Comment by jammsen** [comment]
This will be fixed i think tomorrow, see #40 we are working on it!
