### ISSUE TITLE
[Feature Request] - Daily/scheduled game server restarts if no players connected

### ISSUE THREAD

**Issue by GMBridge** [jammsen/docker-palworld-dedicated-server#50]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

container must be manually restarted (or a system cron job created to restart it) and if players are connected, this risks save file corruption.

### Desired behavior

container uses a daily (or other interval) script against (possible options)
- RCON to see if players are connected, if no players are connected, it restarts the game server or if players are connected then either skips the scheduled reboot or does a broadcast message to the server that the reboot is pending in XX minutes
- if RCON isn't a good option, can the incoming UDP datagrams be monitored and if no UDP traffic in YY interval, declare server is 'idle' and restart game server?

why this is needed: early access games typically have memory leaks that over time lead to poor performance or file corruption. less risk of corrupting saves if restarted with no players connected.

### To Reproduce

1. new feature request

### Software setup

- OS: centos
- Docker: 25.0

### Hardware setup

- vCPU: 6
- RAM: 16
- Disk: 2tb

**Comment by jammsen** [comment]
Hey @GMBridge the new exit-trap-handler should softly exit the game now and not kill it totally. I assume the server saves before but im not sure ... 🤷 

Regarding the other stuff, please look at #27 the part about rcon things before stop.

**Comment by thejcpalma** [comment]
Will look into this for the server restart feature I'm implementing, will discuss it with @jammsen on the best way to do it 😊
Feel free to spark ideas or links for us to be inspired ✨
