### ISSUE TITLE
[Feature Request] - Automatically update game server files if server is idle

### ISSUE THREAD

**Issue by GMBridge** [jammsen/docker-palworld-dedicated-server#51]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

need to manually restart container to download & apply updates from steam to game server

### Desired behavior

check with XX interval if updated game server files are available from steam, then if new files are detected, check if server is 'idle' (either via RCON to get player count or by monitoring for a lack of UDP traffic), if server is idle, apply the update & restart game server. if server is not idle, RCON broadcast a message to let players know there is a pending update that needs to be applied.

### To Reproduce

1. new feature request

### Software setup

- OS: centos
- Docker: 25.0

### Hardware setup

- vCPU: 6
- RAM: 16
- Disk: 2tb

**Comment by jammsen** [comment]
Hey @GMBridge nice idea, thanks for the feature request. This could take a bit of time though, as you can see there are more problems then 1 and adding features comes when every thing else is stable 😄 

Leaving this here as inspiration:
https://github.com/Didstopia/7dtd-server/blob/master/update_check.sh

**Comment by GMBridge** [comment]
i really like how lloesche handled stuff in their valheim container, may also have some good ideas for things  https://github.com/lloesche/valheim-server-docker

**Comment by thejcpalma** [comment]
Will look into this for the server restart feature I'm implementing, will discuss it with @jammsen on the best way to do it 😊
Feel free to spark more ideas or links for us to be inspired ✨

**Comment by thejcpalma** [comment]
### Feature

Auto update server when no players are connected (`X` amount of time between checks for version) . 
Willing to hear suggestions on this implementation.

Willing to implement this feature.

> [!WARNING] 
> Will only work when `RCON` is enabled, as it will need to fetch player info and the only way to obtain that currently is with `RCON`.

Depends on #181

**Comment by jammsen** [comment]
This is fixed in the release on latest from 5 minutes ago. See Changelogs or Discord message regarding the new release and what to lookout for. We dont cover the idle part, but you can setup restarts via Cron-Expressions, which should help you out.

Im closing this issue as resolved, feel free to reach out again if you need help.

If you like this project, please consider giving this repo and the [Docker-Hub-Repo](https://hub.docker.com/repository/docker/jammsen/palworld-dedicated-server) a Star.
