### ISSUE TITLE
[Bug] Server Crash

### ISSUE THREAD

**Issue by CleryMenuel** [jammsen/docker-palworld-dedicated-server#53]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

About every 30 minutes 1 hour the server crashes

### Desired behavior

docker version 2.24.0

### Links to screenshots

![Capture d'écran 2024-01-24 214625](https://github.com/jammsen/docker-palworld-dedicated-server/assets/91963215/767afb48-a471-439f-b9bc-300df1364e1c)
![Capture d'écran 2024-01-24 214258](https://github.com/jammsen/docker-palworld-dedicated-server/assets/91963215/d13c5a2c-6881-4f03-b5e9-dd2c96b80cc4)
![Capture d'écran 2024-01-24 214207](https://github.com/jammsen/docker-palworld-dedicated-server/assets/91963215/05e5b28f-159a-439c-aec6-78e9096f5ff5)
![Capture d'écran 2024-01-24 214128](https://github.com/jammsen/docker-palworld-dedicated-server/assets/91963215/2727bf05-5f2e-44e4-998b-dc664ecd9ef0)

### Software setup

- OS:Debian12
- Docker:2.24.0

### Hardware setup

- vCPU: 
- RAM: 16
- Disk:258go SSD

**Comment by jammsen** [comment]
"Ran out of memory" 👍

**Comment by CleryMenuel** [comment]
This would mean that my server doesn't have enough RAM?

**Comment by jammsen** [comment]
Palworld has GIANT memory leaks on the client and server side. You have to calculate for that. If your Docker-Node runs other services you might have not enough RAM. I would suggest at least 8GB for 4-6 players.

**Comment by jammsen** [comment]
Is this issue resolved?

**Comment by su-bob** [comment]
I used 16GB Memory machine for 10 people. Our friends have trouble with losing connection after 1-2 hours, so when I monitored memory it, the server was shut down and restarted due to memory leak. The memory share decreased to 1GB and then started to increase again.

**Comment by jammsen** [comment]
Im closing this issue as resolved, feel free to reach out again if you need help.

If you like this project, please consider giving this repo and the docker-hub-repo a Star.
