### ISSUE TITLE
Feature-Request: Please add a License

### ISSUE THREAD

**Issue by Dashboy1998** [jammsen/docker-palworld-dedicated-server#55]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

Currently there is not license file in the repository.

### Desired behavior

There should a license file so others know the licensing of the project.

### To Reproduce

View repository

### Software setup

N/A

### Hardware setup

N/A

**Comment by jammsen** [comment]
Hey @Dashboy1998 good point, i dont have any on any on my Docker based server. Never thought of it and never thought i need it.

Any good suggestions i can look into?

**Comment by Alexnortung** [comment]
Imo MIT should be fine

[This site](https://choosealicense.com/) gives a good overview

**Comment by jammsen** [comment]
Added a license.

Im closing this issue as resolved, feel free to reopen again if needed.

If you like this project, please consider giving this repo and the docker-hub-repo a Star.
