### ISSUE TITLE
how to get back v0.1.2.0

### ISSUE THREAD

**Issue by AtomBoyC** [jammsen/docker-palworld-dedicated-server#58]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

I tried all docker images tags, could not back to v0.1.2.0

### Desired behavior

It's updated automatively. I want to back v0.1.2.0 is that possible?

### To Reproduce

none

### Software setup

linux

### Hardware setup

- vCPU: 4h
- RAM: 16g
- Disk:220g

**Comment by jammsen** [comment]
Hey @AtomBoyC 
Why would you want back to an older version?

You might be able to do this after some research in steamcmd here https://developer.valvesoftware.com/wiki/SteamCMD (maybe the --beta option, not sure) and the versions here https://steamdb.info/app/2394010/info/ - Big Maybe!

**Comment by AtomBoyC** [comment]
Thank you for your kind help. Maybe I don't need that. lol

**Comment by wibureview** [comment]
> Thank you for your kind help. Maybe I don't need that. lol

did you find a solution to downgrade to version 0.1.2.0?

**Comment by doodoori2** [comment]
I did small research for next version update. 
There is no way to install specific version in SteamCmd. 

If you want avoid force update, set false ALWAYS_UPDATE_ON_START option in docker compose. 


You can change the server image branch from SteamCmd to -beta option. 
But the only branch released at Palworld is the latest server image.

**Comment by jammsen** [comment]
Im closing this issue as resolved, feel free reopen again if needed.

If you like this project, please consider giving this repo and the docker-hub-repo a Star.
