### ISSUE TITLE
[Feature Request] ENV Var for Tickrate

### ISSUE THREAD

**Issue by stormDE** [jammsen/docker-palworld-dedicated-server#64]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

In some cases for Experimenting, its useful to Set the tickrate lower. this can be be done in _/Pal/Saved/Config/LinuxServer/Engine.ini_ 
and paste at the bottom of the file following lines:

`[/Script/OnlineSubsystemUtils.IpNetDriver]`
`NetServerMaxTickRate=60`

### Desired behavior

Please Add an ENV like `NetServerMaxTickRate=30`

### Links to screenshots

Some Reddit post: https://www.reddit.com/r/Palworld/comments/19avqax/comment/kip5w5w/?utm_source=share&utm_medium=web2x&context=3

### To Reproduce

Nothing to reproduce.

### Software setup

- OS: Ubuntu 22.04 LTS
- Docker:  20.10.21

### Hardware setup

- vCPU: 6
- RAM:  16GB
- Disk: SSD 200GB

### Additional context

This Container is Awesome!

**Comment by jammsen** [comment]
Hey @stormDE thanks for the FR.
Few questions arise here:
* Is there something official that Palworld does support this?
* What is the default value of the setting?
* Does it matter if we put it into Engine.ini or PalWorldsettings.ini? I tend to agree with the "jbo-guy" on here: https://www.reddit.com/r/Palworld/comments/19avqax/comment/kip5w5w/?tm_source=share&utm_medium=web2x&context=3

**Comment by stormDE** [comment]
Hi @jammsen,

I don't know exactly if it would be accepted in another config file, unfortunately these are undocumented settings... But I would take the following statements from this reddit or github ist post. 

more details under https://www.reddit.com/r/Palworld/comments/19f6i19/optimizing_palworld_dedicated_server_engineini/

https://gist.github.com/blackjack4494/628748503c182f5cae04ddacd1e453fa


Thanks!

**Comment by jammsen** [comment]
I have added the functionality, please go ahead and try it, the variable is in the readme, im updating now the docker-compose examples with it.

**Comment by jammsen** [comment]
Examples are finished too!

**Comment by stormDE** [comment]
tested and it worked! Thanks so much!

**Comment by jammsen** [comment]
Im closing this issue as resolved, feel free to reach out again if you need help.

If you like this project, please consider giving this repo and the docker-hub-repo a Star.
