### ISSUE TITLE
[Bug Report] Unsupported environment variable

### ISSUE THREAD

**Issue by Reymouth** [jammsen/docker-palworld-dedicated-server#66]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

When I change the EXP_RATE values to 1.200000 and PAL_EGG_DEFAULT_HATCHING_TIME to 18.000000
The above variables are not applied to the configuration file (PalWorldSettings.ini). All float values may be affected

However, the console displays the expected values:
palworld | Setting ExpRate to 1.200000
palworld | Setting PalEggDefaultHatchingTime to 18.000000

### Desired behavior

Support for values implemented in environment variables.

### To Reproduce

Add the following environment variables and check the configuration file (PalWorldSettings.ini) after the server starts.

    environment:
      - EXP_RATE=1.200000
      - PAL_EGG_DEFAULT_HATCHING_TIME=18.000000

### Software setup

- OS: Debian 12
- Docker: Docker 25.0.1

### Hardware setup

- vCPU: I7 8700K
- RAM:  64G
- Disk: 500G

**Comment by jammsen** [comment]
Hey @Reymouth i dont fully understand, can you please post your `PalWorldSettings.ini` that is generated from the servermanager please.

**Comment by Reymouth** [comment]
The files are below:

docker-compose.yml :
https://paste.pichax.fr/hecuqilayu.http

PalWorldSettings.ini :
https://paste.pichax.fr/udahanotov.ini

If I manually edit the PalWorldSettings.ini file, the values are not replaced by the variables defined in docker-compose.yml

**Comment by Todddday** [comment]
Same here. I read the log and notice that the setting is applied, but PalWorldSettings.ini remains the same.

**Comment by vulnguard** [comment]
After some debugging it seems that the sed command doesn't update some config options correctly due not using extended regex in the sed command (-E). Simple fix by adding -E to the sed commands.

**Comment by jammsen** [comment]
Good morining everyone, seem like i did miss something in that over 5 hours update, im so sorry for that. I will right look into this now. I tought i tested everything by replacing every 1.0000 to 2.0000 but i guess not every system might be equal.

**Comment by jammsen** [comment]
> The files are below:
> 
> docker-compose.yml : https://paste.pichax.fr/hecuqilayu.http
> 
> PalWorldSettings.ini : https://paste.pichax.fr/udahanotov.ini
> 
> If I manually edit the PalWorldSettings.ini file, the values are not replaced by the variables defined in docker-compose.yml

Thank you very much! This helps!

**Comment by jammsen** [comment]
Oh wow after some extensive in detail testing i found out that i did miss a parameter (BUILD_OBJECT_DETERIORATION_DAMAGE_RATE) and quite a few regex scenarios that werent either covered or just simply not triggerin. Im very very sorry for that, my bad 😢 

Here is now a an example of it all working:

```
$ docker exec -ti palworld-dedicated-server cat /palworld/DefaultPalWorldSettings.ini
; This configuration file is a sample of the default server settings.
; Changes to this file will NOT be reflected on the server.
; To change the server settings, modify Pal/Saved/Config/LinuxServer/PalWorldSettings.ini.
[/Script/Pal.PalGameWorldSettings]
OptionSettings=(Difficulty=None,DayTimeSpeedRate=1.000000,NightTimeSpeedRate=1.000000,ExpRate=1.000000,PalCaptureRate=1.000000,PalSpawnNumRate=1.000000,PalDamageRateAttack=1.000000,PalDamageRateDefense=1.000000,PlayerDamageRateAttack=1.000000,PlayerDamageRateDefense=1.000000,PlayerStomachDecreaceRate=1.000000,PlayerStaminaDecreaceRate=1.000000,PlayerAutoHPRegeneRate=1.000000,PlayerAutoHpRegeneRateInSleep=1.000000,PalStomachDecreaceRate=1.000000,PalStaminaDecreaceRate=1.000000,PalAutoHPRegeneRate=1.000000,PalAutoHpRegeneRateInSleep=1.000000,BuildObjectDamageRate=1.000000,BuildObjectDeteriorationDamageRate=1.000000,CollectionDropRate=1.000000,CollectionObjectHpRate=1.000000,CollectionObjectRespawnSpeedRate=1.000000,EnemyDropItemRate=1.000000,DeathPenalty=All,bEnablePlayerToPlayerDamage=False,bEnableFriendlyFire=False,bEnableInvaderEnemy=True,bActiveUNKO=False,bEnableAimAssistPad=True,bEnableAimAssistKeyboard=False,DropItemMaxNum=3000,DropItemMaxNum_UNKO=100,BaseCampMaxNum=128,BaseCampWorkerMaxNum=15,DropItemAliveMaxHours=1.000000,bAutoResetGuildNoOnlinePlayers=False,AutoResetGuildTimeNoOnlinePlayers=72.000000,GuildPlayerMaxNum=20,PalEggDefaultHatchingTime=72.000000,WorkSpeedRate=1.000000,bIsMultiplay=False,bIsPvP=False,bCanPickupOtherGuildDeathPenaltyDrop=False,bEnableNonLoginPenalty=True,bEnableFastTravel=True,bIsStartLocationSelectByMap=True,bExistPlayerAfterLogout=False,bEnableDefenseOtherGuildPlayer=False,CoopPlayerMaxNum=4,ServerPlayerMaxNum=32,ServerName="Default Palworld Server",ServerDescription="",AdminPassword="",ServerPassword="",PublicPort=8211,PublicIP="",RCONEnabled=False,RCONPort=25575,Region="",bUseAuth=True,BanListURL="https://api.palworldgame.com/api/banlist.txt")

$ docker exec -ti palworld-dedicated-server cat /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini
; This configuration file is a sample of the default server settings.
; Changes to this file will NOT be reflected on the server.
; To change the server settings, modify Pal/Saved/Config/LinuxServer/PalWorldSettings.ini.
[/Script/Pal.PalGameWorldSettings]
OptionSettings=(Difficulty=None1,DayTimeSpeedRate=3.000000,NightTimeSpeedRate=3.000000,ExpRate=3.000000,PalCaptureRate=3.000000,PalSpawnNumRate=3.000000,PalDamageRateAttack=3.000000,PalDamageRateDefense=3.000000,PlayerDamageRateAttack=3.000000,PlayerDamageRateDefense=3.000000,PlayerStomachDecreaceRate=3.000000,PlayerStaminaDecreaceRate=3.000000,PlayerAutoHPRegeneRate=3.000000,PlayerAutoHpRegeneRateInSleep=3.000000,PalStomachDecreaceRate=3.000000,PalStaminaDecreaceRate=3.000000,PalAutoHPRegeneRate=3.000000,PalAutoHpRegeneRateInSleep=3.000000,BuildObjectDamageRate=3.000000,BuildObjectDeteriorationDamageRate=3.000000,CollectionDropRate=3.000000,CollectionObjectHpRate=3.000000,CollectionObjectRespawnSpeedRate=3.000000,EnemyDropItemRate=3.000000,DeathPenalty=All1,bEnablePlayerToPlayerDamage=false0,bEnableFriendlyFire=false0,bEnableInvaderEnemy=true1,bActiveUNKO=false0,bEnableAimAssistPad=true1,bEnableAimAssistKeyboard=false0,DropItemMaxNum=2999,DropItemMaxNum_UNKO=99,BaseCampMaxNum=127,BaseCampWorkerMaxNum=14,DropItemAliveMaxHours=3.500000,bAutoResetGuildNoOnlinePlayers=false0,AutoResetGuildTimeNoOnlinePlayers=73.000000,GuildPlayerMaxNum=19,PalEggDefaultHatchingTime=73.000000,WorkSpeedRate=3.000000,bIsMultiplay=false0,bIsPvP=false0,bCanPickupOtherGuildDeathPenaltyDrop=false0,bEnableNonLoginPenalty=true1,bEnableFastTravel=true1,bIsStartLocationSelectByMap=true1,bExistPlayerAfterLogout=false0,bEnableDefenseOtherGuildPlayer=false0,CoopPlayerMaxNum=2,ServerPlayerMaxNum=31,ServerName="jammsen-test-local",ServerDescription="Palworld-Dedicated-Server running in Docker by jammsen1",AdminPassword="adminPasswordHere1",ServerPassword="serverPasswordHere1",PublicPort=8212,PublicIP="22333",RCONEnabled=false0,RCONPort=25576,Region="1",bUseAuth=true1,BanListURL="https://api.palworldgame.com/api/banlist.txt123")
```
As you can see the upper version is a standard Default Config and the down version is a config file so wrong and cringe-worthy that i get goosebumps and im also baffled that the server still starts ... Fix is coming shortly.

**Comment by jammsen** [comment]
This should be working in combination of the new readme from yesterday, please go ahead and try this and give me feedback please.

**Comment by exovdo** [comment]
I am experiencing the same thing, some ENV's are not being applied or changed. I ended up backing up my compose and .ini files and then removed the .ini file completely from the directory and rebooted my VM.

Here is my docker compose file:
https://pastebin.com/WChdDV8C

Upon startup of the server and docker it generated this .ini file:
https://pastebin.com/aB4FaqWz

Going to change some stuff around with my compose for fun. The main thing I'd like to get working is the TickRate, would love to see if 120 fixes some of the jitters.

**Comment by LilDrunkenSmurf** [comment]
This appears to still be happening to me. I'm trying to set `PAL_EGG_DEFAULT_HATCHING_TIME=2` and `DEATH_PENALTY=ItemAndEquipment`, and it's not being picked up. I'm using kubernetes, and all my other values are being picked up.
<https://github.com/LilDrunkenSmurf/k3s-home-cluster/blob/main/kubernetes/teyvat/apps/games/palworld/app/helmrelease.yaml#L40-L54>

```
steam@palworld-6cf4c5d48b-45x22:/palworld/Pal/Saved/Config/LinuxServer$ cat PalWorldSettings.ini
OptionSettings=(Difficulty=None,DayTimeSpeedRate=1.000000,NightTimeSpeedRate=1.000000,ExpRate=1.000000,PalCaptureRate=1.000000,PalSpawnNumRate=1.000000,PalDamageRateAttack=1.000000,PalDamageRateDefense=1.000000,PlayerDamageRateAttack=1.000000,PlayerDamageRateDefense=1.000000,PlayerStomachDecreaceRate=1.000000,PlayerStaminaDecreaceRate=1.000000,PlayerAutoHPRegeneRate=1.000000,PlayerAutoHpRegeneRateInSleep=1.000000,PalStomachDecreaceRate=1.000000,PalStaminaDecreaceRate=1.000000,PalAutoHPRegeneRate=1.000000,PalAutoHpRegeneRateInSleep=1.000000,BuildObjectDamageRate=1.000000,BuildObjectDeteriorationDamageRate=1.000000,CollectionDropRate=1.000000,CollectionObjectHpRate=1.000000,CollectionObjectRespawnSpeedRate=1.000000,EnemyDropItemRate=1.000000,DeathPenalty=All,bEnablePlayerToPlayerDamage=False,bEnableFriendlyFire=False,bEnableInvaderEnemy=True,bActiveUNKO=False,bEnableAimAssistPad=True,bEnableAimAssistKeyboard=False,DropItemMaxNum=3000,DropItemMaxNum_UNKO=100,BaseCampMaxNum=128,BaseCampWorkerMaxNum=15,DropItemAliveMaxHours=1.000000,bAutoResetGuildNoOnlinePlayers=False,AutoResetGuildTimeNoOnlinePlayers=72.000000,GuildPlayerMaxNum=20,PalEggDefaultHatchingTime=72.000000,WorkSpeedRate=1.000000,bIsMultiplay=False,bIsPvP=False,bCanPickupOtherGuildDeathPenaltyDrop=False,bEnableNonLoginPenalty=True,bEnableFastTravel=True,bIsStartLocationSelectByMap=True,bExistPlayerAfterLogout=False,bEnableDefenseOtherGuildPlayer=False,CoopPlayerMaxNum=4,ServerPlayerMaxNum=32,ServerName="LDS-Palworld-Server",ServerDescription="Palworld Server Running on Kubernetes",AdminPassword="<yoink>",ServerPassword="<yoin>",PublicPort=8211,PublicIP="10.0.0.1",RCONEnabled=false,RCONPort=25575,Region="",bUseAuth=True,BanListURL="https://api.palworldgame.com/api/banlist.txt")
```

**Comment by jammsen** [comment]
> This appears to still be happening to me. I'm trying to set `PAL_EGG_DEFAULT_HATCHING_TIME=2` and `DEATH_PENALTY=ItemAndEquipment`, and it's not being picked up. I'm using kubernetes, and all my other values are being picked up. https://github.com/LilDrunkenSmurf/k3s-home-cluster/blob/main/kubernetes/teyvat/apps/games/palworld/app/helmrelease.yaml#L40-L54
> 
> ```
> steam@palworld-6cf4c5d48b-45x22:/palworld/Pal/Saved/Config/LinuxServer$ cat PalWorldSettings.ini
> OptionSettings=(Difficulty=None,DayTimeSpeedRate=1.000000,NightTimeSpeedRate=1.000000,ExpRate=1.000000,PalCaptureRate=1.000000,PalSpawnNumRate=1.000000,PalDamageRateAttack=1.000000,PalDamageRateDefense=1.000000,PlayerDamageRateAttack=1.000000,PlayerDamageRateDefense=1.000000,PlayerStomachDecreaceRate=1.000000,PlayerStaminaDecreaceRate=1.000000,PlayerAutoHPRegeneRate=1.000000,PlayerAutoHpRegeneRateInSleep=1.000000,PalStomachDecreaceRate=1.000000,PalStaminaDecreaceRate=1.000000,PalAutoHPRegeneRate=1.000000,PalAutoHpRegeneRateInSleep=1.000000,BuildObjectDamageRate=1.000000,BuildObjectDeteriorationDamageRate=1.000000,CollectionDropRate=1.000000,CollectionObjectHpRate=1.000000,CollectionObjectRespawnSpeedRate=1.000000,EnemyDropItemRate=1.000000,DeathPenalty=All,bEnablePlayerToPlayerDamage=False,bEnableFriendlyFire=False,bEnableInvaderEnemy=True,bActiveUNKO=False,bEnableAimAssistPad=True,bEnableAimAssistKeyboard=False,DropItemMaxNum=3000,DropItemMaxNum_UNKO=100,BaseCampMaxNum=128,BaseCampWorkerMaxNum=15,DropItemAliveMaxHours=1.000000,bAutoResetGuildNoOnlinePlayers=False,AutoResetGuildTimeNoOnlinePlayers=72.000000,GuildPlayerMaxNum=20,PalEggDefaultHatchingTime=72.000000,WorkSpeedRate=1.000000,bIsMultiplay=False,bIsPvP=False,bCanPickupOtherGuildDeathPenaltyDrop=False,bEnableNonLoginPenalty=True,bEnableFastTravel=True,bIsStartLocationSelectByMap=True,bExistPlayerAfterLogout=False,bEnableDefenseOtherGuildPlayer=False,CoopPlayerMaxNum=4,ServerPlayerMaxNum=32,ServerName="LDS-Palworld-Server",ServerDescription="Palworld Server Running on Kubernetes",AdminPassword="<yoink>",ServerPassword="<yoin>",PublicPort=8211,PublicIP="10.0.0.1",RCONEnabled=false,RCONPort=25575,Region="",bUseAuth=True,BanListURL="https://api.palworldgame.com/api/banlist.txt")
> ```

@LilDrunkenSmurf Please try the latest image an again, this is working for me, i just create a confuse config with all values weird off by 1 or even All1, true1 and false0 values, the go in the file and i can see all of them.

If you still have problems, please create a new issue

The other topic seems to be resolved, thats why im inactivity closing this.
