### ISSUE TITLE
[Bug Report] Incompatible game version

### ISSUE THREAD

**Issue by craigers521** [jammsen/docker-palworld-dedicated-server#69]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

Joining server from client i get an incompatible game version error.  I tried to docker compose down and re-up again, same error.  I tried to pull the latest image manually and build myself, same error. I tried manually running steamcmd to update the app, same error.  Seems like its not updating properly, no idea why. 

### Desired behavior

Able to join server from client 

### To Reproduce

Join server from client

### Software setup

- OS: ubuntu22.04
- Docker: 

### Hardware setup

- vCPU: 8
- RAM: 16GB
- Disk:200GB

**Comment by craigers521** [comment]
idk what happened, and downed and re-upped the container again, still not working, then on ran the steamcmd force update again from inside the container and now its working... sorry for the noise.

**Comment by jammsen** [comment]
Happy it works! No noise here, im here to help!
