### ISSUE TITLE
COMMUNITY_SERVER variable default

### ISSUE THREAD

**Issue by brenix** [jammsen/docker-palworld-dedicated-server#7]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

The README states that the default value for COMMUNITY_SERVER is set to `false`. However, in the Dockerfile and docker-compose files, it is set to `true`. Therefore, if you start the container without this environment variable set, it will default to `true` given the logic in `servermanager.sh` file. One must explicitly set `COMMUNITY_SERVER=false` if you do not wish to add it to the list of community servers. I think this requires clarification in the README or a code change to ensure it is set to false by default.

### Desired behavior

When starting the container without the COMMUNITY_SERVER environment variable set, it should not append the `EpicApp=PalServer` argument, unless explicitly set to true

### To Reproduce

```
$ docker run --rm -it --entrypoint /bin/sh docker.io/jammsen/palworld-dedicated-server
$ env | grep COMMUNITY
COMMUNITY_SERVER=true
```

### Software setup

-

### Hardware setup

-

**Comment by jammsen** [comment]
Yes you are totall right, my bad, it happend between fixing a lot of bugs yesterday, im sorry.
The desired behavior is that its set to true and the documentation should reflect that.

Without Communiy-Server your server will not be listed ingame, which one would want.

**Comment by brenix** [comment]
No worries, just pointing it out :)

**Comment by jammsen** [comment]
Hey @brenix 
Please have a look, should be much clearer now.

**Comment by brenix** [comment]
Lgtm, thanks!
