### ISSUE TITLE
[Bug Report] Var NIGHTTIME_SPEEDRATE is not changable

### ISSUE THREAD

**Issue by lnsflive** [jammsen/docker-palworld-dedicated-server#70]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

In the compose.yml file doesn't seem to change the `NIGHTTIME_SPEEDRATE` setting
I have only needed to update variables that were strings and not sure if `sed` is an issue here, but noticed this variable didn't change in my `PalworldSettings.ini` file

you also mentioned the world setting generator and noticed they are using integers or shorter floats and don't know which to use.

### Desired behavior

would like the `NIGHTTIME_SPEEDRATE` environment variable to be able to change when bringing up and down container using compose

### To Reproduce

1. docker-compose down
2. edit the compose.yml file
3. look for NIGHTTIME_SPEEDRATE=1.000000
4. change to NIGHTTIME_SPEEDRATE=5.000000
5. docker-compose up -d
6. check \Pal\Saved\Config\LinuxServer\PalWorldSettings.ini
7. still shows NightTimeSpeedRate=1.000000

### Software setup

- OS: Linux
- Docker: 20.10.23

### Hardware setup

- vCPU: 4
- RAM: 16gb
- Disk: 10.5 TB

**Comment by vulnguard** [comment]
Same fix as https://github.com/jammsen/docker-palworld-dedicated-server/issues/66#issuecomment-1911270274

**Comment by jammsen** [comment]
This should be working in combination of the new readme from yesterday, please go ahead and try this and give me feedback please.

**Comment by lnsflive** [comment]
yea seems to be working now

**Comment by jammsen** [comment]
Im closing this issue as resolved, feel free reopen again if needed.

If you like this project, please consider giving this repo and the docker-hub-repo a Star.
