### ISSUE TITLE
[Bug Report] Can not Change Config File

### ISSUE THREAD

**Issue by mattholy** [jammsen/docker-palworld-dedicated-server#72]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

every time I restart server the config file seems restored as before.

### Desired behavior

After first start, stop the server, setup your config at game/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini and start it again.
It should work.

### To Reproduce

NA

### Software setup

- OS:Ubuntu
- Docker:docker compose

### Hardware setup

- vCPU: 96
- RAM: 256G
- Disk:20TB

**Comment by jammsen** [comment]
Hey @mattholy yes the config-handling changed massively on request of the community yesterday, please look at the new readme.

**Comment by jammsen** [comment]
Working on a fix for a little bug in there, but in 30m it should be released.

**Comment by mattholy** [comment]
many thanks thats realy a great work

**Comment by jammsen** [comment]
> many thanks thats realy a great work

Happy to hear that, im here to help 👍
