### ISSUE TITLE
PalWorld.sh not found

### ISSUE THREAD

**Issue by SwannHERRERA** [jammsen/docker-palworld-dedicated-server#8]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

server crash when someone try to join

### Desired behavior

people can join the server and play

### Links to screenshots

palworld-dedicated-server  | Connecting anonymously to Steam Public...OK
palworld-dedicated-server  | Waiting for client config...OK
palworld-dedicated-server  | Waiting for user info...OK
palworld-dedicated-server  |  Update state (0x11) preallocating, progress: 0.00 (0 / 4729437191)
palworld-dedicated-server  | Error! App '2394010' state is 0x202 after update job.
palworld-dedicated-server  | >>> Starting the gameserver
palworld-dedicated-server  | Checking for config
palworld-dedicated-server  | /servermanager.sh: line 48: ./PalServer.sh: No such file or directory
palworld-dedicated-server  | >>> Doing a fresh install of the gameserver
palworld-dedicated-server  | tid(11) burning pthread_key_t == 0 so we never use it
palworld-dedicated-server  | Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
palworld-dedicated-server  | Logging directory: '/home/steam/Steam/logs'
palworld-dedicated-server  | [  0%] Checking for available updates...
palworld-dedicated-server  | [----] Verifying installation...
palworld-dedicated-server  | Steam Console Client (c) Valve Corporation - version 1705108307
palworld-dedicated-server  | -- type 'quit' to exit --
palworld-dedicated-server  | Loading Steam API...OK
palworld-dedicated-server  |
palworld-dedicated-server  | Connecting anonymously to Steam Public...OK
palworld-dedicated-server  | Waiting for client config...OK
palworld-dedicated-server  | Waiting for user info...OK
palworld-dedicated-server  |  Update state (0x11) preallocating, progress: 0.00 (0 / 4729437191)
palworld-dedicated-server  | Error! App '2394010' state is 0x202 after update job.
palworld-dedicated-server  | >>> Starting the gameserver
palworld-dedicated-server  | Checking for config
palworld-dedicated-server  | /servermanager.sh: line 48: ./PalServer.sh: No such file or directory

### To Reproduce

clone the repo
create a game folder with chmod 777 on it
edit config with correct ip and port
start docker compose 
stop docker compose 
edit game/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini
start docker compose
try to connect with a windows client

### Software setup

- OS: Linux
- Docker: Docker version 24.0.7, build afdd53b

### Hardware setup

- vCPU: x86 family
- RAM:  4go
- Disk: 256 ssd

### Additional context

I didn't go inside the container to create the game directory.
I didn't install steam `steamcmd` and run everything. Maybe it should be add to the documentation if needed

**Comment by atti-exe** [comment]
"palworld-dedicated-server | Error! App '2394010' state is 0x202 after update job."

Error 0x202 is a not enough disk space error. You need around 5-6gb free to download the server files.

**Comment by jammsen** [comment]
Hey @SwannHERRERA 
After some consulting on google, @atti-exe is right, you might just have not enough space or some volumes might be weird on your install.

**Comment by SwannHERRERA** [comment]
Thanks guys, well spotted. I'm in a working configuration. It wasn't an easy mistake to see without you I'd still be there.
