### ISSUE TITLE
[Feature Request] Custom server update source

### ISSUE THREAD

**Issue by dezhishen** [jammsen/docker-palworld-dedicated-server#81]
### Have you read the Important information text above

- [X] Yes i did

### Describe the feature

https://github.com/VeroFess/PalWorld-Server-Unoffical-Fix

This is an unofficial palworld server binary distribution project that fixes some problems with the original server.

### Additional information

- [ ] Would you be willing to help implement this feature?

### Final checks

- [X] I understand that this is a feature request function. I also unterstand that if i use this to report a bug report, that my issue might be un-answered closed.

**Comment by jammsen** [comment]
Hey @dezhishen this raises a truck-load of security concerns for me ....

**Comment by dezhishen** [comment]
> Hey @dezhishen this raises a truck-load of security concerns for me ....这对我来说是一个巨大的安全隐患...

- Even without this feature, we can still manually replace executable files
- We can disable this feature by default and provide safety reminders
- Sometimes we will use mirror server for steam download

**Comment by jammsen** [comment]
I understand that this is my decision, you dont have to tell me. 
This is too much of a giant bag of angry bees, that will hurt you ... im gonna stay away from that.
