### ISSUE TITLE
[Feature Request] how to update game， 

### ISSUE THREAD

**Issue by JoshuaFeng5** [jammsen/docker-palworld-dedicated-server#88]
### Have you read the Important information text above

- [X] Yes i did

### Describe the feature

I want to update game ， how can i do it

### Additional information

- [ ] Would you be willing to help implement this feature?

### Final checks

- [X] I understand that this is a feature request function. I also unterstand that if i use this to report a bug report, that my issue might be un-answered closed.

**Comment by jammsen** [comment]
Try to restart the docker container? 🤣

**Comment by MrMightyNighty** [comment]
Pull the latest image and set `ALWAYS_UPDATE_ON_START=true`

**Comment by jammsen** [comment]
Yeah that too, thanks @MrMightyNighty 🤣
