### ISSUE TITLE
[Bug Report] Connection failed - Time out request

### ISSUE THREAD

**Issue by Astarae** [jammsen/docker-palworld-dedicated-server#89]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

Hello,

So, my problem is : I can't access the server online. Everything works fine locally tho

My port are also well redirected on my router
![image](https://github.com/jammsen/docker-palworld-dedicated-server/assets/38982341/4544b88d-a522-42a2-8ab5-799631d199c0)

I can also see my server online on battlemetrics : https://www.battlemetrics.com/servers/palworld/25714339

I also have these error, idk if it's related or no 
palworld-dedicated-server    | [S_API FAIL] Tried to access Steam interface SteamFriends017 before SteamAPI_Init succeeded.
palworld-dedicated-server    | [S_API FAIL] Tried to access Steam interface STEAMAPPS_INTERFACE_VERSION008 before SteamAPI_Init succeeded.
palworld-dedicated-server    | [S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.

+

I have to change the version from the docker-compose.yml file, 3.9 to 3.3 to run the container, maybe it's related and my bug isn't a bug, but me being an error lol

### Desired behavior

I should be able to connect to the server

### Software setup

- OS: Linux - Debian 11
- Docker:  version 20.10.5
Docker compose : version 1.25.0

### Hardware setup

- vCPU: 4
- RAM: 24
- Disk: SSD emulated

### Additional context

I use a dedicated server from home, with a proxmox server. My server is basically a VM
I don't have any specific firewall rules
When i set up a password, it recognize that a password is required when i try without one

**Comment by Astarae** [comment]
Solved, i reinstall my vm, use debian 12 and update docker compose
+ my port forwading was incorrect, change to TCP to UDP

Ty for your work

**Comment by jammsen** [comment]
Happy to hear that! Have fun gaming! @Astarae
