### ISSUE TITLE
[Bug Report] /home/steam/steamcmd/steamcmd.sh: line 38: /home/steam/steamcmd/linux32/steamcmd: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by Deanwct** [jammsen/docker-palworld-dedicated-server#91]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

when the docker booting, and has some error.
/home/steam/steamcmd/steamcmd.sh: line 38: /home/steam/steamcmd/linux32/steamcmd: cannot execute binary file: Exec format error

### Desired behavior

has no error message

### To Reproduce

1. Go to 'start docker'
2. See error

### Software setup

- OS:
- Docker:

### Hardware setup

nas(cpu N5105)

**Comment by jammsen** [comment]
Hey @Deanwct if you want me to help you, you have to actually willing to be helping me too. Please create a new issue with acutal information about hardware, software, you config, your server versions of docker, how you run this docker-image and so on. There is no way i can be of any help with what you are giving me. Sorry.
