### ISSUE TITLE
[Feature Request] Add environment variable to select game version.

### ISSUE THREAD

**Issue by Splitframe** [jammsen/docker-palworld-dedicated-server#93]
### Have you read the Important information text above

- [X] Yes i did

### Describe the feature

If possible, please add an environment variable which sets the game version that is downloaded.
It's possible in steam, but I think the game devs need to also offer/enable it.

Background is that we updated to 0.1.3 and the server crashed every time there was more than 1 player on the server.
Luckily I had a backup to roll back.

### Additional information

- [ ] Would you be willing to help implement this feature?

### Final checks

- [X] I understand that this is a feature request function. I also unterstand that if i use this to report a bug report, that my issue might be un-answered closed.

**Comment by doodoori2** [comment]
there is no way to downgrade or update speicfic version on SteamCmd API 

If you want avoid force update, set false ALWAYS_UPDATE_ON_START option in docker compose.

**Comment by jammsen** [comment]
Hey @Splitframe 
Afaik SteamCMD does support the -BETA feature but the devs have to implement and release by that standard, there is "nothing" i can do right now.

**Comment by jammsen** [comment]
Im closing this issue as wontfix, feel free to reach out again if you need help.

If you like this project, please consider giving this repo and the [docker-hub-repo](https://hub.docker.com/repository/docker/jammsen/palworld-dedicated-server) a Star.
