### ISSUE TITLE
[Feature Request] Hoping for support Pterodactyl Panel.  thanks!!

### ISSUE THREAD

**Issue by LAIguapi** [jammsen/docker-palworld-dedicated-server#97]
### Have you read the Important information text above

- [X] Yes i did

### Describe the feature

Hi jammsen, I'm glad to browse your content on github, I wonder if you will consider upgrading the content of this repository to egg on Pterodactyl panel in the future, if you can, it would be very grateful to you, thank you very much for your docker repository

### Additional information

- [ ] Would you be willing to help implement this feature?

### Final checks

- [X] I understand that this is a feature request function. I also unterstand that if i use this to report a bug report, that my issue might be un-answered closed.

**Comment by MrMightyNighty** [comment]
It seems like someone is already working on an egg on a different repo: https://github.com/parkervcp/eggs/pull/2671

A little bit off topic: May I ask why you use Pterodactyl? Wouldn't it be easier to use something like Portainer and use the docker-compose file?

**Comment by jammsen** [comment]
Hey @LAIguapi - Thanks for the FR.
I honestly have never once heard of "Pterodactyl Panel" nor have i experience in this. Pretty sure i wont add this in the near future.

If that helps:
A member of the community called @Plarpoon is working on #94 which would be adding a description for an edge-case to use Portainer. 

Also down the line i will for sure make a documentation update for usage of Dockge too, but i have to get my finger in that first.

Sorry i cant be more helpful with this. 😭

**Comment by LAIguapi** [comment]
> It seems like someone is already working on an egg on a different repo: [parkervcp/eggs#2671](https://github.com/parkervcp/eggs/pull/2671)
> 
> A little bit off topic: May I ask why you use Pterodactyl? Wouldn't it be easier to use something like Portainer and use the docker-compose file?

Thanks for your reply , I think this resp will be a valuable example for me.

**Comment by LAIguapi** [comment]
> Hey @LAIguapi - Thanks for the FR. I honestly have never once heard of "Pterodactyl Panel" nor have i experience in this. Pretty sure i wont add this in the near future.
> 
> If that helps: A member of the community called @Plarpoon is working on #94 which would be adding a description for an edge-case to use Portainer.
> 
> Also down the line i will for sure make a documentation update for usage of Dockge too, but i have to get my finger in that first.
> 
> Sorry i cant be more helpful with this. 😭

Hi jammsen , very thanks for your reply . Pterodactyl Panel is a visual panel game server, you can know it by  [here](https://github.com/pterodactyl-china/panel) . 

Thanks for your advice . And also grateful for your Docker Hub

**Comment by jammsen** [comment]
> > Hey @LAIguapi - Thanks for the FR. I honestly have never once heard of "Pterodactyl Panel" nor have i experience in this. Pretty sure i wont add this in the near future.
> > If that helps: A member of the community called @Plarpoon is working on #94 which would be adding a description for an edge-case to use Portainer.
> > Also down the line i will for sure make a documentation update for usage of Dockge too, but i have to get my finger in that first.
> > Sorry i cant be more helpful with this. 😭
> 
> Hi jammsen , very thanks for your reply . Pterodactyl Panel is a visual panel game server, you can know it by [here](https://github.com/pterodactyl-china/panel) .

Looks to me like LinuxGSM or WindowsGSM to be honest with a bit a flair of Dockge.

 
> Thanks for your advice . And also grateful for your Docker Hub

No! Thank you! 😄 *Keanu-Wave*
